primary.cells <- c(
  "stem",  
  "t-lymphocyte", 
  "macrophage", 
  "myoblast", 
  "monocyte", 
  "t cell", 
  "embryonic stem cell", 
  "pluripotent stem cell", 
  "fibroblast", 
  "b cell", 
  "b-lymphocyte",  
  "neuron",  
  "peripheral blood mononuclear cell", 
  "stem cell", 
  "trophoblast", 
  "epithelial cell", 
  "skeletal muscle", 
  "blastocyst", 
  "oral epithelium",
  "granulocyte", 
  "neural crest", 
  "sperm",  
  "hepatocyte", 
  "huvec cell",  
  "hematopoietic stem cell", 
  "hesc cell", 
  "malignant cell", 
  "rostral octaval nerve motor nucleus", 
  "epithelium", 
  # "mature neutrophil", 
  "melanocyte", 
  "oocyte", 
  "osteoblast", 
  "parvocellular oculomotor nucleus", 
  "erythroblast", 
  "keratinocyte", 
  "lymphocyte",
  "blastomere", 
  "bronchial epithelial cell", 
  "endothelium", 
  "germ cell", 
  "leukocyte",
  "neutrophil", 
  "skin fibroblast",
  "astrocyte", 
  "blast cell",
  "endothelial cell", 
  "smooth muscle", 
  "motoneuron", 
  "motor neuron",
  "basal cell", 
  "blood vessel smooth muscle",
  "erythrocyte", 
  "erythroid progenitor cell",
  "mammary gland epithelial cell", 
  "microglia", 
  "microglial cell", 
  "neural stem cell", 
  "neuronal stem cell", 
  "smooth muscle cell",
  "basophil progenitor cell", 
  "blastoderm cell", 
  "blood platelet",
  "breast epithelium", 
  "cancer stem cell", 
  "chondrocyte", 
  "foreskin fibroblast",
  "hepatoblast", 
  "hpsc cell", 
  "ilc1",
  "lung fibroblast",
  "lymphoblast",
  "naive t-lymphocyte", 
  "naive t cell", 
  "neoplastic cell", 
  "olfactory epithelium", 
  "platelet", 
  "preadipocyte", 
  # "professional antigen presenting cell", 
  "t-cell acute lymphoblastic leukemia cell",
  "zygote",
  "animal zygote", 
  "aortic smooth muscle", 
  "cardiac muscle cell", 
  "cardiac muscle fiber", 
  "common myeloid progenitor",
  "conventional dendritic cell", 
  "helper t-lymphocyte",
  "hipsc cell", 
  "intermediate cell mass of mesoderm", 
  "mammary epithelial cell",
  "memory t-lymphocyte", 
  "memory t cell", 
  "pre-b-lymphocyte", 
  "primordial germ cell", 
  "t follicular helper cell", 
  "thp-1 cell", 
  "vascular associated smooth muscle cell", 
  "vascular smooth muscle", 
  "acute myeloid leukemia cell", 
  "adipocyte", 
  "aortic smooth muscle cell", 
  "b-lymphoblastoid cell",
  "basophilic erythroblast",
  "blood cell", 
  "breast cancer cell", 
  "cerebellar granule cell", 
  "cerebral cortical neuron",
  "colonic epithelium", 
  "common lymphoid progenitor", 
  "coronary artery smooth muscle", 
  "dendritic cell",
  "dopaminergic neuron", 
  "early lymphoid progenitor", 
  "epiblast", 
  "epiblast (generic)", 
  "fat cell",
  "glial cell", 
  "glomerular endothelial cell", 
  "granulocyte monocyte progenitor cell", 
  "granulosa cell", 
  "group 2 innate lymphoid cell",
  "hematopoietic cell", 
  "hepatic stellate cell", 
  "innate lymphoid cell", 
  "interneuron", 
  "intestinal epithelium", 
  # "langerhans cell",
  "lung microvascular endothelial cell", 
  "lymphoid cell", 
  "mammary epithelium", 
  "marrow cell", 
  "mast cell",
  "megakaryocyte", 
  "mesangial cell", 
  "mesenchymal cell", 
  "mononuclear cell", 
  "myeloid cell",
  "natural killer cell", 
  "natural t-regulatory cell",
  "non-small cell lung cancer cell", 
  "oligodendrocyte", 
  "pancreatic alpha cell", 
  "pancreatic beta cell",
  "pericyte cell", 
  "peritoneal macrophage", 
  "plasma cell", 
  "polychromatophilic erythroblast",
  "precursor b cell", 
  "pyramidal neuron",
  "radial glial cell", 
  "respiratory epithelium", 
  "respiratory tract epithelium", 
  "spermatocyte", 
  "syncytiotrophoblast", 
  "thyroid epithelial cell", 
  "trophectoderm", 
  "vascular smooth muscle cell", 
  "acinar cell", 
  "acinar",
  "adult stem cell",
  "aorta smooth muscle tissue",
  "breast epithelial cell", 
  "bronchial smooth muscle", 
  "bronchus smooth muscle",
  "calvarial osteoblast", 
  "cd14-positive monocyte", 
  "cd4-positive, cd25-positive, alpha-beta regulatory t cell", 
  "cerebellar purkinje cell", 
  "chronic myeloid leukemia cell", 
  "colorectal cancer cell", 
  "corneal endothelial cell", 
  "corneal endothelium", 
  "corneal epithelium", 
  "cumulus cell", 
  "dermal fibroblast", 
  "effector memory cd8-positive, alpha-beta t cell, terminally differentiated", 
  "embryonic neural stem cell", 
  "endocrine cell", 
  "endometrial microvascular endothelial cells", 
  "endometrial stroma", 
  "endothelial cell of lymphatic vessel", 
  "endothelial cell of umbilical vein", 
  "enucleate erythrocyte", 
  "epidermal stem cell", 
  "epithelial cell of alveolus of lung", 
  "epithelium of esophagus", 
  "epithelium of mammary gland", 
  "epithelium of vagina", 
  "esophageal epithelium", 
  "esophagus muscularis mucosa", 
  "esophagus squamous epithelium", 
  "fibroblast of arm", 
  "fibroblast of lung", 
  "gastrointestinal tract (lamina propria) macrophage", 
  "germinal center b cell", 
  "glia", 
  "glioblastoma cell", 
  "glioma stem cell", 
  "gonadotrophic cell", 
  "group 3 innate lymphoid cell", 
  "hap-1 cell", 
  "haploid cell", 
  "helper t cell", 
  "hemangioblast", 
  "hematopoietic multipotent progenitor cell", 
  "hepatoma cell",
  "hmepc cell", 
  "iga plasmablast", 
  "inflammatory macrophage", 
  "inner cell mass derived hypoblast", 
  "intestinal epithelial cell", 
  "kidney cancer cell", 
  "kidney cell", 
  "kopt-k1 cell", 
  "leukemia cell", 
  "liver sinusoidal endothelial cell", 
  "lung adenocarcinoma cell", 
  "lung cancer cell", 
  "lymphatic endothelial cell", 
  "lymphoid progenitor cell", 
  "m1 macrophage", 
  "male germ cell", 
  "mammary microvascular endothelial cell", 
  "mammary myoepithelial cell",  
  "medulloblastoma cell", 
  "megakaryocyte-erythroid progenitor cell", 
  "melanocyte of skin", 
  "melanoma cell", 
  "mesenchymal stromal cell", 
  "microvascular endothelial cell", 
  "multilaminar epithelium", 
  "muscle stem cell", 
  "myeloid progenitor cell", 
  "naive thymus-derived cd4-positive, alpha-beta t cell", 
  "nasal cavity respiratory epithelium epithelial cell of viscerocranial mucosa", 
  "nerve", 
  "neural cell", 
  "oral epithelial cell", 
  "oral squamous cell carcinoma cell", 
  "orthochromatic erythroblast", 
  "osteosarcoma cell", 
  "ovarian cumulus cell", 
  "ovarian serous carcinoma cell", 
  "ovary cancer cell", 
  "pancreatic islet cell", 
  "pericardium fibroblast", 
  "pericyte", 
  "peripheral blood lymphocyte", 
  "peripheral blood stem cell", 
  "placental epithelial cell", 
  "pneumocyte", 
  "polymorphonuclear leukocyte", 
  "pos cell", 
  "proerythroblast", 
  "pulmonary artery smooth muscle cell", 
  "purkinje cell", 
  "regulatory t-lymphocyte", 
  "regulatory t cell", 
  "respiratory basal cell", 
  "respiratory epithelial cell", 
  "respiratory epithelium cell", 
  "reticulocyte",
  "retinal ganglion cell",
  "retinal pigment epithelial cell", 
  "retinal pigment epithelium cell", 
  "rheumatoid arthritis disease specific synovial fibroblast", 
  "sensory cell", 
  "sensory neuron",
  "smooth muscle cell of the pulmonary artery", 
  "stem cell of epidermis", 
  "stratified epithelium",
  "stroma of bone marrow",
  "t-helper 17 cell", 
  "th17 cell",
  "tibial nerve",
  "type b pancreatic cell", 
  "type i pneumocyte", 
  "urinary bladder cancer cell", 
  "uroepithelium", 
  "vagal neural crest", 
  "vaginal epithelium",
  "hela cell",
  "epithelial cell of gall bladder",
  "epithelial cell of proximal tubule",
  "neuron of cerebral cortex",
  "neuron of the forebrain",
  "oral epithelium",
  # "cd4",
  "signal transducer cd24",
  "cd44 molecule",
  "plasmacytoid dendritic cell",
  "neuroendocrine tumor cell",
  ###From MONDO/MEDDRA###
  "blood monocytes", 
  "blood neutrophils", 
  "lymphocytes", 
  "monocytes", 
  "neutrophils")

cell.lines <- c(
  ### Cell lines ###
  "lncap cell", 
  "nicr576 cell",#	a549 cell
  "nicr91", #293T cell
  "mda-mb-231", #not working?
  "rcb0428 cell", #saos-2 cell
  "molm-13 cell",
  "hek293-t-rex cell",
  "pc-14 cell",
  "hela s3",
  "a-375 cell",
  "786-o cell",
  "22rv1 cell",
  "u2-os cell",
  "arpe-19 cell",
  "bm4 b cell",
  "caco-2 cell",
  "bt-20 cell",
  "hct-116 cell",
  "k-562 cell",
  "mcf-10a cell",
  "mcf-7 cell",
  "mda-mb-231 cell",
  "molm-14 cell",
  "nb-1 cell",
  "nci-h1299 cell",
  "nci-h1975 cell",
  "pc-3 cell",
  "ramos (ra.1) cell",
  "tk-6 cell",
  "u-87mg cell",
  "uacc-257 cell",
  "wa-09 cell",
  "hek-293 cell",
  "hep-g2 cell",
  "t-24 cell", 
  "tf-1 cell", 
  # "nicr1047 cell", 
  "hela cell",
  "rcb1897 cell",
  "hep g2 cell",
  "u-2 os cell", 
  "mda-mb-231",
  "op9 cell",
  "mcf 10a cell",
  "a20 cell",
  "mewo cell",
  # "nicr1002",
  "rcb1904 cell",
  "rcb2143 cell",
  "cfpac-1 cell", 
  "jurkat",
  "kasumi-1 cell",
  "nicr91",
  "rko",
  "sum159pt cell", 
  "rcb0098 cell",
  "cgth-w-1 cell",
  "hela s3", 
  "mda-mb-468 cell",
  "nccit cell",
  "nicr1720",
  "nicr26 cell", 
  "nicr447 cell",
  "huh7 cell",
  "imr-32 cell",
  "nicr204",
  "nicr87 cell", 
  "sw480",
  "tcd5",
  "tk6 cell",
  "293",
  "capan-1 cell", 
  "dohh2 cell",
  "ht-29 cell",
  "nicr1525 cell",
  "nicr2184 cell", 
  "nicr425 cell",
  "nicr815 cell",
  "rcb0202 cell",
  "rcb2138 cell", 
  "rcb2141 cell",
  "arpe-19 cell",
  "gm12878 cell",
  "hcc1954 cell", 
  "hcc827 cell",
  "hek293",
  "hela-s3 cell",
  "mt4 cell", 
  "nicr36 cell",
  "nicr40 cell",
  "nicr422",
  "nicr602",
  "nicr656 cell", 
  "nicr796",
  "rcb0654 cell",
  "rcb0750 cell",
  "rcb0988 cell", 
  "rcb1647 cell",
  "rcb1935 cell",
  "rcb1973 cell",
  "rcb2700 cell",  
  "rt4",
  "sk-n-be(2) cell",
  "143b cell",
  "219 cell",
  "35.6 cell", 
  "3t3-derived cell",
  "a-673 cell",
  "a172 cell",
  "a673 cell",
  "a704 cell", 
  "aa8 cell",
  "ag04450 cell",
  "b11 cell",
  "b12 cell",
  "bc3 cell", 
  "be(2)-c cell",
  "be2 cell",
  "bt-474",
  "c127 cell",
  "c129 cell", 
  "c16 cell",
  "c32 cell",
  "c8166 cell",
  "caco-2 cell",
  "caki-1 cell", 
  "cmk cell",
  "del cell",
  "detroit 551 cell",
  "dg-75 cell",
  "dv-90 cell",
  "g-401 cell",
  "gm03348 cell",
  "gm05372 cell",
  "gm12004 cell", 
  "gm12750 cell",
  "gm12892 cell",
  "hcc1419 cell",
  "hcc1937 cell", 
  "hcc1954 bl cell",
  "hcc4006 cell",
  "hct 116",
  "hff-1 cell", 
  "hgf cell",
  "ishikawa 3-h-12 cell",
  "ishikawa cell",
  "k-562 cell", 
  "karpas-422 cell",
  "l101 cell",
  "loucy cell",
  "lu99a cell",
  "ly2 cell", 
  "m85 cell",
  "m86 cell",
  "mda-mb-436 cell",
  "mda-mb-453 cell", 
  "mkn28 cell",
  "nci-h1944 cell",
  "nci-h358",
  "nci-h460",
  "nci-n87 cell", 
  # "nicr1003",
  # "nicr1110",
  "nicr115 cell",
  "nicr1324",
  "nicr1386", 
  "nicr158 cell",
  "nicr164",
  "nicr1657",
  "nicr1703 cell",
  "nicr1847 cell", 
  "nicr1852 cell",
  "nicr21 cell",
  "nicr2172 cell",
  "nicr2198 cell", 
  "nicr2218",
  "nicr247 cell",
  "nicr265",
  "nicr439 cell",
  "nicr47 cell", 
  "nicr581 cell",
  "nicr661",
  "nicr700 cell",
  "nicr837 cell",
  "nicr85 cell", 
  "nicr975 cell",
  "nicr996",
  "oe33 cell",
  "peer cell", 
  "rcb0041 cell",
  "rcb0193 cell",
  "rcb0431 cell",
  "rcb1001 cell", 
  "rcb1292 cell",
  "rcb2095 cell",
  "reh cell",
  "rwpe-1 cell", 
  "sf268 cell",
  "sh-4 cell",
  "sjcrh30 cell",
  "um-uc-3 cell",
  "rcb4455 cell",
  "rcb0208 cell",
  "c38 cell",
  "dld-1 cell",
  "r63 cell", 
  "b2-1 cell",
  "su-dhl-4 cell",
  "hcc70 cell",
  "nb-4 cell",
  "au565 cell", 
  "c44 cell",
  "hcc3153 cell",
  "huh-1 cell",
  "hcc1569 cell",
  "a11 cell", 
  "f11 cell",
  "hep-2 cell",
  "rcb1933 cell",
  "hek-293t cell",
  "a2058 cell", 
  "hsb-2 cell",
  "sk-mes-1 cell",
  "t98g cell",
  "697 cell",
  "lp-1 cell", 
  "su-dhl-1 cell",
  "suit-2 cell",
  "sw 13 cell",
  "5637 cell",
  "cl2 cell", 
  "su-dhl-10 cell",
  "wa-01 cell",
  "d24 cell",
  "mda-mb-157 cell", 
  "a2780cis cell",
  "b19 cell",
  "bc-3 cell",
  "bgc-823 cell",
  "ch1 cell", 
  "es4 cell",
  "hsc0107 cell",
  "oci-aml3 cell",
  "rcb0186 cell", 
  "rcb1648 cell",
  "saos-2 cell",
  "te7 cell",
  "hec-1 cell",
  "me-1 cell", 
  "mia paca-2 cell",
  "mono-mac-6 cell",
  "mv-4-11 cell",
  "rcb0748 cell", 
  "rcb1164 cell",
  "rcb1375 cell",
  "sh4 cell",
  "sw-480 cell",
  "tf1 cell", 
  "u-266 cell",
  "116 cell",
  "a-498 cell",
  "calu-3 cell",
  "dnd-41 cell", 
  "efo-21 cell",
  "es5 cell",
  "hcc1806 cell",
  "hl-60 cell",
  "ls1034 cell", 
  "ls180 cell",
  "mac-1 cell",
  "mcf-7/lcc9 cell",
  "miapaca-2 cell", 
  "nalm-6 cell",
  "oci-aml2 cell",
  "opm-2 cell",
  "ov-90 cell",
  "p19 cell", 
  "panc-1 cell",
  "rcb0206 cell",
  "rcb1154 cell",
  "rcb1934 cell", 
  "rcb1974 cell",
  "rcb2227 cell",
  "rcb2231 cell",
  "rcb2316 cell", 
  "rpmi-8402 cell",
  "sk-mel-28 cell",
  "t-47d cell",
  "u-251mg cell", 
  "wa-07 cell",
  "ws1 cell",
  "a-1847 cell",
  "a498 cell",
  "ag09429 cell", 
  "bv-173 cell",
  "bxpc-3 cell",
  "caki-2 cell",
  "ccd-1112sk cell", 
  "chl-1 cell",
  "derl-2 cell",
  "detroit 562 cell",
  "es-2 cell", 
  "f24 cell",
  "fhs 74 int cell",
  "gm03651 cell",
  "h9 cell",
  "hc-1 cell", 
  "hcc1143 cell",
  "hdlm-2 cell",
  "hep-2c cell",
  "hfob 1.19 cell", 
  "hsc0013 cell",
  "igrov-1 cell",
  "imr-5 cell",
  "jsc-1 cell",
  "jurkat, clone e6-1 cell", 
  "jvm-2 cell",
  "jvm-3 cell",
  "km-h2 cell",
  "km12 cell",
  "kms-12-bm cell", 
  "kopn-8 cell",
  "l-1236 cell",
  "l-363 cell",
  "l-428 cell",
  "lncap-c4-2 cell", 
  "m15 cell",
  "ms-5 cell",
  "nci-h1581 cell",
  "nci-h2087 cell", 
  "nci-h2110 cell",
  "nci-h2171 cell",
  "nci-h226 cell",
  "nci-h441 cell", 
  "nci-h82 cell",
  "nih:ovcar-3 cell",
  "ovcar-3 cell",
  "plb-985 cell", 
  "rcb0435 cell",
  "rcb0443 cell",
  "rcb0487 cell",
  "rcb0489 cell", 
  "rcb0490 cell",
  "rcb0494 cell",
  "rcb0515 cell",
  "rcb0554 cell", 
  "rcb0657 cell",
  "rcb0660 cell",
  "rcb0665 cell",
  "rcb0680 cell", 
  "rcb0685 cell",
  "rcb0692 cell",
  "rcb0705 cell",
  "rcb0736 cell", 
  "rcb0749 cell",
  "rcb0763 cell",
  "rcb0774 cell",
  "rcb0775 cell", 
  "rcb0776 cell",
  "rcb0789 cell",
  "rcb0803 cell",
  "rcb0805 cell", 
  "rcb0966 cell",
  "rcb0967 cell",
  "rcb0978 cell",
  "rcb0982 cell", 
  "rcb0983 cell",
  "rcb0989 cell",
  "rcb0991 cell",
  "rcb1003 cell", 
  "rcb1009 cell",
  "rcb1012 cell",
  "rcb1018 cell",
  "rcb1130 cell", 
  "rcb1169 cell",
  "rcb1185 cell",
  "rcb1186 cell",
  "rcb1275 cell", 
  "rcb1296 cell",
  "rcb1297 cell",
  "rcb1313 cell",
  "rcb1316 cell", 
  "rcb1317 cell",
  "rcb1367 cell",
  "rcb1374 cell",
  "rcb1376 cell", 
  "rcb1428 cell",
  "rcb1440 cell",
  "rcb1460 cell",
  "rcb1495 cell", 
  "rcb1520 cell",
  "rcb1521 cell",
  "rcb1547 cell",
  "rcb1548 cell", 
  "rcb1558 cell",
  "rcb1591 cell",
  "rcb1676 cell",
  "rcb1702 cell", 
  "rcb1731 cell",
  "rcb1878 cell",
  "rcb1912 cell",
  "rcb1938 cell", 
  "rcb1939 cell",
  "rcb1941 cell",
  "rcb1943 cell",
  "rcb1953 cell", 
  "rcb1960 cell",
  "rcb1965 cell",
  "rcb1967 cell",
  "rcb1970 cell", 
  "rcb1971 cell",
  "rcb1972 cell",
  "rcb1976 cell",
  "rcb1981 cell", 
  "rcb2078 cell",
  "rcb2084 cell",
  "rcb2087 cell",
  "rcb2088 cell", 
  "rcb2093 cell",
  "rcb2094 cell",
  "rcb2102 cell",
  "rcb2105 cell", 
  "rcb2106 cell",
  "rcb2108 cell",
  "rcb2139 cell",
  "rcb2229 cell", 
  "rcb2279 cell",
  "rcb2286 cell",
  "rcb2345 cell",
  "rcb2346 cell", 
  "rcb2350 cell",
  "rcb2362 cell",
  "rcb2364 cell",
  "rcb2534 cell", 
  "rcb2537 cell",
  "rcb2830 cell",
  "rcb2832 cell",
  "rec-1 cell", 
  "rs4;11 cell",
  "rt-112 cell",
  "sf539 cell",
  "sgc-7901 cell", 
  "sk-n-be(2)-c cell",
  "snb-19 cell",
  "snb75 cell",
  "su-dhl-5 cell", 
  "su-dhl-6 cell",
  "sum-149pt cell",
  "sum149pt cell",
  "sup-t1 cell", 
  "sw1463 cell",
  "uwb1.289 cell",
  "wm1552c cell",
  "wm35 cell",
  "breast cancer cell line", 
  "non-small cell lung cancer cell line", 
  "osteosarcoma cell line", 
  "acute myeloid leukemia cell line",
  "human embryonic stem cell line cell",
  "colonic cancer cell line", 
  "hepatoma cell line", 
  "neuroblastoma cell line",
  "burkitt lymphoma cell line", 
  "embryonic stem cell line", 
  "epithelial cell line", 
  "erythroleukemia cell line", 
  "prostate cancer cell line", 
  "melanoma cell line", 
  "pancreatic cancer cell line", 
  "leukemia cell line",
  "b-lymphocyte cell line", 
  "breast adenocarcinoma cell line", 
  "alveolar epithelial cell line", 
  "adenocarcinoma cell line", 
  "breast cell line", 
  "cervical cancer cell line", 
  "colorectal cancer cell line", 
  "gastric cell line", 
  "glioblastoma cell line", 
  "glioblastoma multiforme cell line", 
  "lung adenocarcinoma cell line", 
  "kidney cell line",
  "lung cancer cell line", 
  "lung fibroblast cell line", 
  "medulloblastoma cell line", 
  "multiple myeloma cell line", 
  "myeloma cell line", 
  "ovary cancer cell line", 
  "pancreatic adenocarcinoma cell line", 
  "rhabdomyosarcoma cell line", 
  "squamous cell carcinoma cell line", 
  "t-lymphocyte cell line",
  "thyroid cell line", 
  "human induced pluripotent stem cell line cell",
  "lymphoblastoid cell line",
  "mesenchymal stem cell")

cell.annotations <- c(primary.cells, cell.lines)