list.ethnicities <-list(
  # "--",
  # "a",
  # "a?",
  # "aa",
  "aboriginal" = c("aboriginal"),
  "ad mixed american" = c("multiracial", "american"),
  "admixed" = c("multiracial"), 
  # "adult",
  "afram" = c("african american"),
  "africa american" = c("african american"),
  "african" = c("african"),
  "african america" = c("african american"), 
  "african american" = c("african american"),
  "african americans" = c("african american"),
  "african_american" = c("african american"), 
  "african-american" = c("african american"),
  "african, black" = c("black african"),
  "african/american" = c("african american"),
  "afro-caribbean" = c("african caribbean"), 
  "afro-caribbean descent" = c("african caribbean"),
  "ai" = c("asian"),
  "aisian" = c("asian"),
  "american indian" = c("north american indian"), 
  "american indian or alaska native; white" = c("north american indian", "white"),
  "american indian oralaskanative" = c("north american indian"), 
  "american.indian" = c("north american indian"),
  "amindian/alaskanativ" = c("north american indian"),
  "arab" = c("arabic"),
  "arabic" = c("arabic"), 
  # "as",
  "ashkenazi jew" = c("ashkenazi jewish"),
  "asia" = c("asian"),
  "asian" = c("asian"),
  "asian /asian british- indian" = c("asian", "british", "indian"), 
  "asian; white" = c("asian", "white"),
  # "b",
  "bakiga" = c("bakiga"),
  "batwa" = c("batwa"),
  # "bcell",
  "biracial" = c("multiracial"), 
  "black" = c("black"),
  "black or african american" = c("african american"),
  "black or african american; white" = c("african american", "white"), 
  "black, non-hispanic" = c("african american", "not hispanic or latino"),
  "black/african american" = c("african american"),
  "black/puerto rican" = c("black", "puerto rican"), 
  "boston" = c("american"),
  "brazilian" = c("brazilian"),
  "british" = c("british"),
  "british_indian" = c("british", "indian"),
  "bruneian" = c("bruneian"), 
  # "c",
  # "c?",
  "cambodian" = c("cambodian"),
  "cau" = c("caucasian"),
  "cauc" = c("caucasian"),
  "caucasian" = c("caucasian"),
  "caucasian / white" = c("caucasian", "white"), 
  "caucasian descent" = c("caucasian"),
  "caucasian-hispanic" = c("caucasian", "hispanic or latino"),
  "caucasian/sardinian" = c("caucasian", "sardinian"), 
  "caucasion" = c("caucasian"),
  "caucasoid" = c("caucasian"),
  "caucassian" = c("caucasian"),
  "causasian" = c("caucasian"),
  "causasian jewish" = c("caucasian", "jewish"), 
  "causasian jewish / scandanavian" = c("caucasian", "jewish", "scandanavian"),
  # "cell culture",
  "central european" = c("central european"), 
  "central_africa_cameroon" = c("cameroon"),
  "central_asia_afganistan" = c("afghani"),
  "central_europe_germany" = c("german"), 
  "central_europe_poland" = c("polish"),
  # "ceu",
  # "chb",
  "chinese" = c("chinese"),
  "chinese descent" = c("chinese"), 
  "chinese han" = c("han chinese"),
  "chinese han ethnicity" = c("han chinese"),
  # "chs",
  "clm" = c("colombian"),
  "coloured" = c("colored"), 
  # "cord blood",
  # "cxx",
  "danish" = c("danish"),
  # "disease",
  # "ea",
  # "early passage", 
  "east asian" = c("east asian"),
  "east_africa_somalia" = c("somali"),
  "east_africa_tanzania" = c("tanzanian"), 
  "east_african_kenya" = c("kenyan"),
  "east_african_somalia" = c("somali"),
  "east_african_sudan" = c("sudanese"), 
  "east_african_uganda" = c("ugandan"),
  "east_african_zimbabwe" = c("zimbabwean"),
  "east-asian" = c("east asian"), 
  "eastern sicily" = c("sicilian"),
  # "elp",
  # "endothelial",
  "english" = c("british"),
  "european" = c("european"), 
  "european american" = c("european american"),
  "european americans" = c("european american"),
  "european descent" = c("european"), 
  "european-american" = c("european american"),
  # "fibroblast",
  "filipino" = c("filipino"),
  # "fin",
  "finnish" = c("finnish"), 
  # "for human",
  "fulani" = c("fulani"),
  "fulla" = c("fulla"),
  # "fyx",
  "gb" = c("british"),
  "gbr" = c("british"),
  "german" = c("german"), 
  # "glc",
  # "h",
  "han" = c("han chinese"),
  "han chinese" = c("han chinese"),
  "han chinese in bejing, china (chb)" = c("han chinese"), 
  "han individuals" = c("han chinese"),
  "han nationality" = c("han chinese"),
  "han population" = c("han chinese"),
  "han, chinese" = c("han chinese"), 
  # "hapmap ceu",
  # "hapmap yri",
  "hisp" = c("hispanic or latino"),
  "hispanic" = c("hispanic or latino"),
  "hispanic or latino" = c("hispanic or latino"), 
  "hispanic-latino" = c("hispanic or latino"),
  "hispanic/latino" = c("hispanic or latino"),
  # "homo sapiens",
  # "hsc", 
  # "human",
  # "hzx",
  "indian" = c("indian"),
  "indian/alaska native" = c("north american indian"),
  # "j",
  "japanese" = c("japanese"), 
  "japanese in tokyo, japan (jpt)" = c("japanese"),
  "jola" = c("jola"),
  # "k",
  "kenyan" = c("kenyan"),
  "korean" = c("korean"), 
  "latin" = c("hispanic or latino"),
  "latino" = c("hispanic or latino"),
  "latino/hispanic" = c("hispanic or latino"),
  # "leucocytes",
  # "lmpp",
  # "lsf", 
  # "lwg",
  "lwk" = c("luhya"),
  # "lyj",
  "malay" = c("malay"),
  # "malignant",
  "mandingo" = c("mandingo"),
  "manjago" = c("manjago"), 
  "maori" = c("maori"),
  "maya" = c("maya"),
  "mbuti pygmy" = c("mbuti"),
  "melanesian" = c("melanesian"),
  "missing" = c("unspecified"),
  "mixed" = c("multiracial"), 
  "mixed race" = c("multiracial"),
  "morroco" = c("morrocan"),
  "mossi" = c("mossi"),
  "mozabite" = c("mozabite"),
  # "mpp",
  "multiple race" = c("multiracial"), 
  "n/a" = c("unspecified"),
  # "na",
  "natam" = c("north american indian"),
  "native american" = c("north american indian"),
  # "nb",
  # "nd",
  "netherlands" = c("dutch"), 
  "nh" = c("not hispanic or latino"),
  "non_hispanic" = c("not hispanic or latino"),
  "non-hispanic" = c("not hispanic or latino"),
  "non-hispanic white" = c("not hispanic or latino", "white"),
  "non-hispanic/non-latino" = c("not hispanic or latino"), 
  "north america" = c("north america"),
  "north indian" = c("north indian"),
  "not applicable" = c("unspecified"),
  "not available" = c("unspecified"), 
  "not collected" = c("unspecified"),
  "not determined" = c("unspecified"),
  "not hispanic or latino" = c("not hispanic or latino"), 
  "not hispanic/latino" = c("not hispanic or latino"),
  "not reported" = c("unspecified"),
  "not-collected" = c("unspecified"),
  # "nut midline carcinoma", 
  "oriental" = c("asian"),
  "other" = c("unspecified"),
  # "other npc",
  "other/mixed" = c("multiracial"),
  "pacific islander" = c("pacific islander"), 
  "pakistani" = c("pakistani"),
  # "pan immune",
  "pathan" = c("pathan"),
  # "pbmc",
  # "pediatric",
  # "peripheral blood", 
  "persian" = c("persian"),
  "polish" = c("polish"),
  # "preprob",
  # "prob",
  "pur" = c("puerto rican"),
  "qatari" = c("qatari"),
  "russian" = c("russian"), 
  "san" = c("san"),
  "singaporean" = c("singaporean"),
  "somalian" = c("somali"),
  "south african" = c("south african"),
  "south america" = c("south american"), 
  "south american" = c("south american"),
  "south asian" = c("south asian"),
  "south indian" = c("south indian"),
  "south korean" = c("south korean"), 
  "south_asia_bangladesh" = c("bangladeshi"),
  "south_asia_isc" = c("indian"),
  "south_asia_pakistan" = c("pakistani"), 
  "south_asia_sri_lanka" = c("sri lankan"),
  "spain" = c("spanish"),
  # "suzhou",
  "taiwanese" = c("taiwanese"),
  "thai" = c("thai"), 
  "tibetan individuals" = c("tibetan"),
  # "tqy",
  # "trdv",
  # "tsi",
  # "u",
  "ugandan" = c("ugandan"), 
  "unable to obtain" = c("unspecified"),
  "unavailable" = c("unspecified"),
  "unk" = c("unspecified"),
  "unknown" = c("unspecified"),
  "unknown or not reported" = c("unspecified"), 
  # "us - seld identified",
  "utah/mormon" = c("mormon", "american"),
  # "w",
  # "w/asian",
  # "wdf", 
  "western_europe_holland" = c("dutch"),
  "white" = c("white"),
  "white - other" = c("white", "unspecified"),
  "white - white british" = c("white", "british"), 
  "white or caucasian" = c("white", "caucasian"),
  "white, caucasian" = c("white", "caucasian"),
  "white, non-hispanic" = c("white", "not hispanic or latino"), 
  "white, not hispanic" = c("white", "not hispanic or latino"),
  "white; american indian or alaska native" = c("north american indian", "white"), 
  "white; asian" = c("white", "asian"),
  "white; other" = c("white", "unspecified"),
  "white; white" = c("white"),
  "white/american" = c("white", "american"), 
  "white/caucasian" = c("white", "caucasian"),
  "white/east indian" = c("white", "east indian"),
  "white/not hispanic" = c("white", "not hispanic or latino"), 
  "wollof" = c("wollof"),
  # "wxj",
  "xanthoderm" = c("asian"),
  "xathoderm" = c("asian"),
  # "xsm",
  # "xxz",
  "yakut" = c("yakut"), 
  "yellow race" = c("asian"),
  "yoruba" = c("yoruba"),
  "yri" = c("nigerian"),
  # "yxq",
  # "zfc",
  "zulu" = c("zulu")
)
