meaningful_treatments <- c(
  "4'-epidoxorubicin",
  "abatacept",
  "abemaciclib",
  "abiraterone",
  # "acetate",
  # "acetone",
  # "acetylene",
  "acetylsalicylic acid",
  "acriflavine", 
  # "actinomycin d",
  # "activated charcoal",
  "acyclovir",
  "adalimumab", 
  # "adenine",
  # "adenosine",
  "afatinib",
  # "agar",
  # "alanine",
  "albendazole", 
  # "alcohol",
  "alectinib",
  "alendronic acid",
  "alginate",
  # "alkyne", 
  "allopurinol",
  "alprazolam",
  "amikacin",
  "amiloride",
  "aminacrine", 
  "aminoglycoside",
  "amiodarone",
  "amlexanox", 
  "amlodipine",
  # "amoxicillin",
  "ampicillin",
  "amprolium",
  "amsacrine", 
  "anagrelide",
  "anakinra",
  # "analgesic function",
  # "androgen",
  "androstane", 
  "aprepitant",
  # "arginine",
  "arsenic trioxide",
  "ascorbic acid", 
  # "asparaginase",
  # "asparagine",
  "atorvastatin",
  "axitinib", 
  "azacitidine",
  "azathioprine",
  "azithromycin",
  # "bacillus subtilis", 
  "bcg vaccine",
  "bedaquiline",
  "belimumab",
  "belinostat",
  "benzalkonium", 
  # "benzodiazepine",
  "berberine",
  "bevacizumab",
  "bexarotene",
  "bezafibrate", 
  "bicalutamide",
  "bioallethrin",
  "bleomycin",
  "bortezomib", 
  "bosentan",
  "bosutinib",
  "budesonide",
  "bupivacaine",
  "busulfan", 
  "cabazitaxel",
  "cabozantinib",
  "caffeine",
  "calcipotriene",
  # "calcitriol", 
  # "calcium",
  # "calcium chloride",
  "candesartan",
  # "candida albicans", 
  "cantharidin",
  "capsaicin",
  "carbamazepine",
  "carbenicillin", 
  # "carbohydrate",
  # "carbon dioxide",
  "carboplatin",
  "carfilzomib", 
  "carmustine",
  "carnosine",
  # "cefaclor",
  # "cefadroxil",
  "cefepime", 
  # "cellulose",
  "ceritinib",
  "cetuximab",
  # "charcoal",
  "chloramphenicol", 
  # "chlordiazepoxide",
  "chloroquine",
  # "chlorpromazine",
  "chlorprothixene", 
  # "cholesterol",
  # "choline",
  "ciclopirox",
  "cisplatin",
  "citrulline", 
  "cladribine",
  # "clarithromycin",
  "clofarabine",
  "clonidine",
  "cobimetinib", 
  # "cocaine",
  # "collagen",
  "copanlisib",
  "copper",
  # "creatine",
  "crizotinib", 
  "curcumin",
  "cyclophosphamide",
  "cyclosporin a",
  "cysteamine", 
  # "cysteine",
  "cytarabine",
  # "d-biotin",
  "dabrafenib",
  "daratumumab", 
  "darunavir",
  "dasatinib",
  "daunorubicin",
  "decitabine",
  "definition", 
  "denosumab",
  "dexamethasone",
  # "dextran",
  # "didanosine",
  "digoxin",
  # "dimethicone polymer",
  # "dimethyl ether",
  # "dimethyl sulfoxide", 
  # "dinucleotide",
  # "dipeptide",
  "disulfiram",
  "docetaxel trihydrate",
  # "dopamine",
  "doxorubicin",
  "doxycycline",
  # "edetic acid",
  "emetine", 
  "empagliflozin",
  "enalapril",
  "entrectinib",
  "enzalutamide", 
  "epigallocatechin gallate",
  "eribulin",
  "erlotinib",
  # "escherichia coli", 
  "escitalopram",
  "esomeprazole",
  # "ester",
  "estradiol",
  # "estrogen", 
  # "estrogens",
  # "estrone",
  "etanercept",
  "ethambutol",
  # "ethanol", 
  # "ether",
  "ethionamide",
  "etoposide",
  "everolimus",
  "exemestane", 
  # "factor ix",
  # "fatty acid",
  # "fiber",
  "filgrastim",
  "fingolimod", 
  "flecainide",
  # "floxuridine",
  # "flucytosine",
  "fludarabine",
  "fluorouracil", 
  "fluvastatin",
  # "folate",
  # "formaldehyde",
  "formoterol",
  "fostamatinib", 
  # "fructose",
  "fulvestrant",
  "fumarate",
  # "function",
  "gabapentin", 
  # "galactose",
  "gefitinib",
  # "gelatin",
  "gemcitabine",
  # "gentamicin", 
  "ginsenoside",
  "glimepiride",
  "glipizide",
  # "glucan",
  "glucocorticoid", 
  # "glucosamine",
  # "glucose",
  # "glutamate",
  # "glutamine",
  # "glutathione", 
  # "glycerin",
  # "glycerone",
  # "glycine betaine",
  # "glycosaminoglycan", 
  # "glycoside",
  "golimumab",
  "hematoporphyrin",
  "hemin",
  # "heparin", 
  # "hepatitis b immune globulin",
  # "hexachlorocyclohexane",
  # "histamine", 
  # "histidine",
  # "history",
  # "hyaluronic acid",
  # "hydrocarbon",
  # "hydrochloric acid", 
  "hydrochlorothiazide",
  "hydrocortisone",
  # "hydrogen atom",
  # "hydrogen peroxide", 
  # "hydroxamic acid",
  "hydroxychloroquine",
  "hydroxyurea",
  "ibrutinib", 
  "ibuprofen",
  "idarubicin",
  "idelalisib",
  "imatinib",
  "imiquimod", 
  "infliximab",
  "inositol",
  "interferon-beta",
  # "iodine",
  # "ion", 
  "irbesartan",
  "irinotecan",
  # "iron",
  "isotretinoin",
  "isoxaflutole", 
  "istradefylline",
  "itraconazole",
  "ivacaftor",
  "ixabepilone", 
  "ixazomib",
  "ketamine",
  # "krill oil",
  # "lactate",
  # "lactobacillus",
  "lactobacillus rhamnosus gg",
  # "lactone",
  # "lactose",
  "lapatinib", 
  "leflunomide",
  "lenalidomide",
  "lenvatinib",
  "letrozole",
  # "leucine", 
  "leucovorin",
  "leuprolide",
  "levamisole",
  # "lignan",
  # "lipid", 
  "lisinopril",
  "lithium atom",
  "loperamide",
  "lorlatinib",
  "lovastatin", 
  "lumacaftor",
  # "lysine",
  # "magnesium",
  # "magnesium chloride",
  # "maltose", 
  # "mannose",
  # "mass",
  "mebendazole",
  "mechlorethamine",
  "medroxyprogesterone", 
  "melphalan",
  "mercaptopurine",
  # "mercury",
  "meropenem",
  # "metal atom", 
  "metformin",
  # "methamphetamine",
  # "methanol",
  # "methicillin",
  # "methionine", 
  "methotrexate",
  "methoxamine",
  # "methyldopa",
  "methylprednisolone", 
  # "mica",
  "milrinone",
  # "mineral oil",
  # "mineralocorticoid",
  "misoprostol", 
  "mitomycin",
  "mitotane",
  "mitoxantrone",
  # "mixture",
  # "molecule", 
  # "monocarboxylic acid anion",
  "montelukast",
  "mycophenolic acid", 
  # "nad",
  # "nad zwitterion",
  "naproxen",
  "nebivolol",
  # "neisseria meningitidis", 
  "neomycin",
  "neratinib",
  "nicardipine",
  "nicotinamide",
  "nicotinamide nucleotide", 
  "nicotine",
  "nilotinib",
  "nintedanib",
  "nivolumab",
  "noradrenaline", 
  "norepinephrine",
  "nortriptyline",
  # "nucleic acid",
  # "nucleoside", 
  # "nucleotide",
  "octreotide",
  "olaparib",
  # "oligosaccharide",
  # "organism", 
  "osimertinib",
  "ouabain",
  "oxaliplatin",
  # "oxide",
  # "oxygen",
  # "p-aminohippuric acid", 
  "paclitaxel",
  "palbociclib",
  "panobinostat",
  # "papain",
  "paracetamol", 
  # "paraffin",
  # "parathyroid hormone",
  "paromomycin",
  "paroxetine", 
  "parthenolide",
  "pazopanib",
  "pembrolizumab",
  "pentamidine", 
  # "pentose",
  "pentostatin",
  "pentoxifylline",
  # "peptide",
  "perhexiline", 
  "permethrin",
  "pertussis vaccine",
  # "phenobarbital",
  "phentolamine", 
  "phenylalanine",
  # "phosphate",
  # "phosphatidylserine",
  "phosphoethanolamine", 
  "pilocarpine",
  "pioglitazone",
  "pirfenidone",
  # "placebo",
  "plerixafor",
  # "polyamine macromolecule",
  # "polyethylene glycols",
  "polymyxin", 
  # "polyol",
  # "polypeptide",
  # "polysaccharide",
  "pomalidomide",
  "ponatinib", 
  # "potassium",
  # "potassium chloride",
  # "potassium hydroxide",
  # "potassium phosphate", 
  "prednisolone",
  # "process",
  # "progesterone",
  # "proline",
  "propafenone", 
  # "propane-1,2-diol",
  "propranolol",
  "propylthiouracil",
  # "prostaglandin", 
  # "protein",
  # "protein binding",
  # "proteins",
  # "pyruvate",
  # "quality", 
  "quercetin",
  "quetiapine",
  "quinine",
  # "radical",
  "raloxifene", 
  "raltitrexed",
  # "reactive oxygen species",
  "regorafenib",
  # "resistance to infection", 
  "resveratrol",
  "retinoic acid",
  "retinoid",
  "ribociclib",
  "rifampicin", 
  "riociguat",
  "rituximab",
  # "rna",
  # "role",
  "romidepsin",
  "rosiglitazone", 
  "rucaparib",
  "ruxolitinib",
  # "s-adenosyl-l-methionine",
  "saccharin", 
  # "saccharomyces cerevisiae",
  "salmeterol",
  # "salt",
  # "saturated fatty acid", 
  # "scattered molecular aggregate",
  "selinexor",
  # "serine",
  "sevoflurane", 
  # "short-chain fatty acid",
  "simvastatin",
  # "site",
  # "sodium",
  # "sodium bicarbonate", 
  # "sodium chloride",
  # "sodium fluoride",
  # "sodium iodide",
  # "sodium valproate", 
  # "somatotropin",
  "sorafenib",
  # "sorbitol",
  # "steroid",
  # "steroid hormone", 
  # "subset",
  # "sucrose",
  "sulconazole",
  "sulfamethoxazole",
  "sulfasalazine", 
  "sulfonamide",
  # "sulfur",
  "sunitinib",
  "tacrolimus",
  "tagraxofusp", 
  # "tamoxifen",
  "telmisartan",
  "temozolomide",
  "temsirolimus",
  "teniposide", 
  "terbinafine",
  # "testosterone",
  # "tetracycline",
  "thalidomide", 
  "thapsigargin",
  "thiabendazole",
  # "thiol",
  "thiostrepton",
  "thrombin", 
  # "thymine",
  "tobramycin",
  "tocilizumab",
  "tofacitinib",
  "tolbutamide", 
  "topotecan",
  "toremifene",
  "trametinib",
  "trastuzumab",
  # "treatment", 
  "trehalose",
  "tretinoin",
  "triamcinolone",
  # "triclocarban",
  "tricyclic antidepressant", 
  # "trypsin",
  # "tryptophan",
  # "tyrosine",
  # "ubidecarenone",
  # "uridine", 
  "ustekinumab",
  "vandetanib",
  "vedolizumab",
  "vemurafenib",
  "venetoclax", 
  "vinblastine",
  "vincristine",
  "vindesine",
  "vinorelbine",
  "vismodegib", 
  "vitamin d",
  "vitamin d3",
  "vitamin e",
  "vorinostat",
  # "water", 
  # "zinc",
  "zoledronic acid")
