non_meaningfull_disease_annotations <- 
  c("accident",
  "acetaminophen",
  "acetone",
  "acquired",
  "adhesion", 
  "adrenalectomy",
  "aldosterone",
  "animal",
  "antiviral treatment", 
  "apheresis",
  "apoptosis",
  "ascites",
  "autograft",
  "autopsy", 
  "basophils",
  "bed rest",
  "biopsy",
  "biopsy of liver",
  "biopsy of stomach", 
  "bird",
  "blast cells",
  "bleeding",
  "blister",
  "blood donor", 
  "blood eosinophils",
  "blood monocytes",
  "blood neutrophils", 
  "body system",
  "bone biopsy",
  "bone fracture",
  "bone lesion", 
  "bone marrow biopsy",
  "br-",
  "brain biopsy",
  "brca3",
  "breast reduction", 
  "bromide",
  "bronchial biopsy",
  "bronchoalveolar lavage",
  "c-section", 
  "cadmium",
  "caffeine",
  "calcium",
  "cancer pain",
  "cardiac biopsy", 
  "cat",
  "cbc",
  "cell",
  "cell death",
  "cervical biopsy",
  "cesarean section", 
  "chemical",
  "chemotherapy",
  "childhood",
  "chloride",
  "cholesterol", 
  "chromium",
  "cl-",
  "classification",
  "co2",
  "colectomy",
  "colon biopsy", 
  "colonic biopsy",
  "copper",
  "cortisol",
  "cpap",
  "craniotomy", 
  "culture",
  "cyclic amp",
  "cyst",
  "death",
  "delivery",
  "diaphragm", 
  "discectomy",
  "disease or disorder",
  "disease progression",
  "disseminated", 
  "edema",
  "effusion",
  "elderly",
  "endometrial biopsy",
  "endoscopic biopsy", 
  "enzyme",
  "eosinophils",
  "erythroblasts",
  "esophageal biopsy", 
  "esterase c",
  "estradiol",
  "estrogen",
  "ethanol",
  "eukaryote", 
  "euthanasia",
  "ex-smoker",
  "fertilisation",
  "fetal distress", 
  "fibrin",
  "fibrosis",
  "finding",
  "fish",
  "flow cytometry",
  "fracture", 
  "fructose",
  "ganglion",
  "gas",
  "gastric banding",
  "gastric bypass", 
  "globulin",
  "glucose",
  "group",
  "gun shot wound",
  "hanging", 
  "hdl",
  "heart transplant",
  "hematuria",
  "hemodialysis",
  "her2 negative", 
  "hiv negative",
  "homicide",
  "hormone",
  "human",
  "hyperplasia", 
  "hypertrophic scar",
  "hysterectomy",
  "iga",
  "igd",
  "ige",
  "igg", 
  "igm",
  "illness",
  "immunocompromised",
  "induced abortion",
  "inherited", 
  "injury",
  "interactions",
  "interferon gamma release assay",
  "intoxication", 
  "jet lag",
  "keloid",
  "kidney biopsy",
  "kidney transplant",
  "lactate", 
  "ldl",
  "lead",
  "limb ischemia",
  "liver biopsy",
  "liver resection", 
  "liver transplant",
  "localized",
  "lumbar puncture",
  "lung biopsy", 
  "lung transplant",
  "lymphadenectomy",
  "magnesium",
  "manganese", 
  "mass",
  "methanol",
  "monocytes",
  "motor vehicle accident",
  "mri", 
  "mucosal biopsy",
  "muscle biopsy",
  "muscle injury",
  "muscle mass", 
  "na+",
  "necrosis",
  "nephrectomy",
  "nervous",
  "newborn",
  "nodule", 
  "non-smoker",
  "nonsmoker",
  "normal pregnancy",
  "not rare",
  "null", 
  "nulliparous",
  "orchiectomy",
  "organism",
  "orphan",
  "oxidative stress", 
  "p24",
  "pale",
  "paracentesis",
  "paracetamol",
  "partial nephrectomy", 
  "pcr",
  "pcr positive",
  "peritoneal dialysis",
  "peritoneal effusion", 
  "phosphoglycoprotein 1",
  "plant",
  "pleural effusion",
  "potassium", 
  "pregnancy",
  "pregnant",
  "preterm labor",
  "progesterone",
  "prostatectomy", 
  "prostatic biopsy",
  "protein",
  "proteinuria",
  "psa",
  "pth",
  "pygmy", 
  "radical nephrectomy",
  "radical prostatectomy",
  "radiofrequency ablation", 
  "radiotherapy",
  "rare",
  "receptor",
  "rectal biopsy",
  "renin", 
  "reptile",
  "separation",
  "sheath",
  "sinus rhythm",
  "skin biopsy", 
  "skin punch biopsy",
  "smoker",
  "sodium",
  "spontaneous abortion", 
  "sputum",
  "surgery",
  "synovial biopsy",
  "tendon injury",
  "term birth", 
  "testosterone",
  "thrombin",
  "thrombus",
  "thymectomy",
  "tissue", 
  "total knee replacement",
  "transplant",
  "trauma",
  "traumatic delivery", 
  "tumor necrosis",
  "tumor resection",
  "tumor thrombosis",
  "twin pregnancy", 
  "ulcer",
  "vaccination",
  "vaginal delivery",
  "vaginal prolapse", 
  "varicose vein",
  "vesicle",
  "vesicles",
  "vitamin e",
  "wart", 
  "washed-out",
  "wbc",
  "weight",
  "wilms tumor 4",
  "wilms tumor 5", 
  "wilms tumor 6",
  "withdrawn",
  "wound",
  "x-ray")