real_study_diseases <- c(
  "3p- syndrome",
  "7q11.23 microduplication syndrome",
  "abdominal mass", 
  "abdominal tumor",
  "acantholytic variant squamous cell breast carcinoma", 
  "acinar cell carcinoma",
  "acinic cell carcinoma",
  "acne",
  "acne (disease)", 
  "acne inversa",
  "acne vulgaris",
  "acral lentiginous melanoma (disease)", 
  "acromegaly",
  "actinic keratosis",
  "actinic keratosis (disease)", 
  "active tuberculosis",
  "acute angle-closure glaucoma",
  "acute cellular rejection", 
  "acute closed-angle glaucoma",
  "acute erythroid leukemia",
  "acute kidney failure", 
  "acute leukemia",
  "acute leukemia (disease)",
  "acute leukemia of ambiguous lineage", 
  "acute lymphoblastic leukaemia",
  "acute lymphoblastic leukemia", 
  "acute lymphoblastic leukemia (disease)",
  "acute lymphocytic leukemia", 
  "acute megakaryoblastic leukaemia",
  "acute megakaryoblastic leukemia", 
  "acute monocytic leukemia",
  "acute mountain sickness",
  "acute myeloblastic leukemia", 
  "acute myeloblastic leukemia with maturation",
  "acute myeloid leukemia", 
  "acute myeloid leukemia with abnormal bone marrow eosinophils inv(16)(p13q22) or t(16;16)(p13;q22)", 
  "acute myelomonocytic leukemia",
  "acute myelomonocytic leukemia m4", 
  "acute myocardial infarction",
  "acute promyelocytic leukemia", 
  "acute renal failure",
  "acute t cell leukemia",
  "adamantinoma", 
  "adamantinous craniopharyngioma",
  "adenocarcinoma",
  "adenocarcinoma in situ", 
  "adenocarcinoma lung",
  "adenocarcinoma nos",
  "adenocarcinoma of colon", 
  "adenocarcinoma of lung",
  "adenofibroma",
  "adenoid cystic carcinoma", 
  "adenoma",
  "adenomatous colon polyp",
  "adenosarcoma",
  "adenosine deaminase deficiency", 
  "adenosquamous carcinoma",
  "adenosquamous cell carcinoma",
  "adenosquamous lung carcinoma", 
  "adhd",
  "adrenal cortex adenoma",
  "adrenal cortex carcinoma", 
  "adrenal gland myelolipoma",
  "adrenal mass",
  "adrenal myelolipoma", 
  "adrenocortical carcinoma",
  "adult extraskeletal osteosarcoma", 
  "adult glioblastoma",
  "adult t-cell leukemia/lymphoma",
  "advanced heart failure", 
  "agammaglobulinemia",
  "age-related macular degeneration",
  "aggressive nk-cell leukemia", 
  "aggressive periodontitis",
  "agvhd",
  "aids",
  "alagille syndrome", 
  "alcohol abuse",
  "alcohol use",
  "alcohol use disorder",
  "alcoholic", 
  "alcoholic fatty liver disease",
  "alcoholic hepatitis",
  "alcoholic liver disease", 
  "alcoholic liver diseases",
  "alexander disease",
  "alk-negative anaplastic large cell lymphoma", 
  "alk-positive anaplastic large cell lymphoma",
  "allergic asthma", 
  "allergic bronchopulmonary aspergillosis",
  "allergic disease", 
  "allergic rhinitis",
  "alopecia",
  "alopecia areata",
  "alpha 1-antitrypsin deficiency", 
  "als",
  "alveolar cell carcinoma",
  "alveolar rhabdomyosarcoma", 
  "alveolar rhabdomyosarcoma (disease)",
  "alveolar soft part sarcoma", 
  "alveolar soft part sarcoma (disease)",
  "alzheimer disease", 
  "alzheimer's disease",
  "amelanotic melanoma",
  "ameloblastoma", 
  "amyloidosis (disease)",
  "amyotrophic lateral sclerosis",
  "anaplastic astrocytoma", 
  "anaplastic carcinoma",
  "anaplastic ependymoma",
  "anaplastic large cell lymphoma", 
  "anaplastic large-cell lymphoma",
  "anaplastic oligodendroglioma", 
  "anaplastic thyroid cancer",
  "anastomotic stenosis",
  "androgenetic alopecia", 
  "anemia",
  "aneurysm",
  "angiocentric glioma",
  "angiofibroma", 
  "angioimmunoblastic t-cell lymphoma",
  "angiolipoma",
  "angioma", 
  "angiomyolipoma",
  "angiosarcoma",
  "angiosarcoma (disease)",
  "ankylosing spondylitis", 
  "anoxia",
  "anthrax infection",
  "antibody-mediated rejection", 
  "antiphospholipid syndrome",
  "aortic aneurysm",
  "aortic aneurysm (disease)", 
  "aortic dissection",
  "aortic valve disease 2",
  "aortic valve replacement", 
  "ards",
  "arhinia, choanal atresia, and microphthalmia",
  "aria", 
  "arrhythmogenic right ventricular cardiomyopathy",
  "arteriosclerosis disorder", 
  "arthralgia",
  "arthritis",
  "aspergillosis",
  "aspergillus fumigatus infection", 
  "asphyxia",
  "asplenia",
  "asthenozoospermia",
  "asthma",
  "asthmatic", 
  "astrocytoma",
  "ataxia",
  "ataxia telangiectasia",
  "ataxic",
  "atherosclerosis", 
  "atopic",
  "atopic asthma",
  "atopic dermatitis",
  "atresia of small intestine", 
  "atrial fibrillation",
  "atrial fibrillation (disease)",
  "atrophic gastritis", 
  "atrophy",
  "atypical chronic myeloid leukemia",
  "atypical fibroxanthoma", 
  "atypical teratoid rhabdoid tumor",
  "autism",
  "autism (disease)", 
  "autism spectrum disorder",
  "autoimmune disease",
  "autoimmune hepatitis", 
  "autoimmune thrombocytopenic purpura",
  "autoinflammatory disease", 
  "autoinflammatory syndrome with immune deficiency",
  "autosomal dominant polycystic kidney disease", 
  "azoospermia",
  "b-cell acute lymphoblastic leukemia",
  "b-cell adult acute lymphocytic leukemia", 
  "b-cell chronic lymphocytic leukemia",
  "b-cell lymphoma",
  "b-cell neoplasm", 
  "bacterial infection",
  "bacterial infectious disease",
  "bacterial sepsis", 
  "bardet-biedl syndrome",
  "barrett esophagus",
  "barrett's esophagus", 
  "basal cell carcinoma",
  "basal-like breast carcinoma",
  "benign adult familial myoclonic epilepsy", 
  "benign fibrous histiocytoma",
  "benign prostatic hyperplasia", 
  "benign prostatic hyperplasia (disease)",
  "bicuspid aortic valve", 
  "bile duct cancer",
  "bile duct carcinoma",
  "biliary atresia", 
  "biliary tract cancer",
  "biphasic mesothelioma",
  "bipolar disorder", 
  "bizarre leiomyoma",
  "bladder cancer",
  "bladder carcinoma",
  "bladder squamous cell carcinoma", 
  "bladder transitional cell carcinoma",
  "blau syndrome",
  "bloom syndrome", 
  "blue cone monochromacy",
  "bone cancer",
  "bone chondrosarcoma", 
  "bone giant cell tumor",
  "bone marrow cancer",
  "bone marrow failure", 
  "bone neoplasm",
  "bone osteosarcoma",
  "borna disease",
  "borst-jadassohn intraepidermal carcinoma", 
  "bowel obstruction",
  "bph",
  "brain aneurysm",
  "brain astrocytoma", 
  "brain cancer",
  "brain glioblastoma",
  "brain glioma",
  "brain injury", 
  "brain lesion",
  "brain neoplasm",
  "brain tumor",
  "branchiooculofacial syndrome", 
  "breast adenocarcinoma",
  "breast adenomyoepithelioma",
  "breast cancer", 
  "breast carcinoma",
  "breast ductal adenocarcinoma",
  "breast ductal carcinoma", 
  "breast fibrocystic",
  "breast fibrocystic disease",
  "breast lobular carcinoma", 
  "breast neoplasm",
  "brenner tumor",
  "bronchial dysplasia",
  "bronchioalveolar carcinoma", 
  "bronchiolitis (disease)",
  "bronchitis",
  "bronchogenic carcinoma", 
  "bronchopulmonary dysplasia",
  "brucellosis",
  "brugada syndrome", 
  "bruton-type agammaglobulinemia",
  "burkitt lymphoma",
  "burkitt's lymphoma", 
  "burn",
  "bursitis",
  "cadasil",
  "calcinosis",
  "cancer of prostate", 
  "carcinoid tumor (disease)",
  "carcinoma",
  "carcinoma brain", 
  "carcinoma ex pleomorphic adenoma",
  "carcinoma hepatocellular", 
  "carcinoma in situ",
  "carcinoma liver",
  "carcinoma of esophagus", 
  "carcinoma of liver and intrahepatic biliary tract",
  "carcinoma of pharynx", 
  "carcinoma squamous",
  "carcinosarcoma",
  "cardiac arrest",
  "cardiac rhabdomyoma (disease)", 
  "cardiomegaly",
  "cardiomyopathy",
  "cardiomyopathy, familial restrictive, 1", 
  "cardiovascular disease",
  "cardiovascular insufficiency",
  "carotid body tumor", 
  "carotid stenosis",
  "carpal tunnel syndrome",
  "carpal tunnel syndrome 1", 
  "cartilage-hair hypoplasia",
  "castration-resistant prostate cancer", 
  "cataract",
  "cataracts",
  "cd4+/cd56+ hematodermic neoplasm", 
  "celiac disease",
  "central nervous system cancer",
  "central nervous system germinoma", 
  "central neurocytoma",
  "cerebellar hypoplasia",
  "cerebral cavernous malformation", 
  "cerebral cortical dysplasia",
  "cerebral hemorrhage",
  "cerebral malaria", 
  "cerebrovascular accident",
  "cerebrovascular disorder",
  "cervical adenocarcinoma", 
  "cervical cancer",
  "cervical carcinoma",
  "cervical intraepithelial neoplasia", 
  "cervical squamous cell carcinoma",
  "cervical squamous intraepithelial neoplasia", 
  "cervix carcinoma",
  "chagas disease",
  "charcot-marie-tooth disease", 
  "charcot-marie-tooth disease type 1a",
  "charcot-marie-tooth disease type 3", 
  "chikungunya",
  "childhood acute lymphoblastic leukemia",
  "childhood acute myeloid leukemia", 
  "childhood bladder carcinoma",
  "childhood ependymoma",
  "childhood leukemia", 
  "chlamydia trachomatis infectious disease",
  "choanal atresia", 
  "cholangiocarcinoma",
  "cholera",
  "cholestatic hepatitis",
  "cholesteatoma", 
  "cholesteatoma (disease)",
  "chondroblastoma",
  "chondroblastoma (disease)", 
  "chondrosarcoma",
  "chondrosarcoma (disease)",
  "chordoma",
  "chordoma (disease)", 
  "chorioamnionitis",
  "choriocarcinoma",
  "choriocarcinoma of testis", 
  "chronic angle-closure glaucoma",
  "chronic atrophic gastritis", 
  "chronic closed-angle glaucoma",
  "chronic fatigue syndrome", 
  "chronic hepatitis",
  "chronic hepatitis b",
  "chronic hepatitis c", 
  "chronic iron overload",
  "chronic kidney disease",
  "chronic leukemia", 
  "chronic liver disease",
  "chronic lymphocytic leukemia",
  "chronic mucocutaneous candidiasis", 
  "chronic myelogenous leukemia",
  "chronic myelogenous leukemia, bcr-abl1 positive", 
  "chronic myeloid leukemia",
  "chronic myelomonocytic leukemia", 
  "chronic nasopharyngitis",
  "chronic obstructive pulmonary disease", 
  "chronic pain",
  "chronic pancreatitis",
  "chronic periodontitis", 
  "chronic phase chronic myeloid leukemia",
  "chronic recurrent multifocal osteomyelitis", 
  "chronic recurrent multifocal osteomyelitis (disease)",
  "chronic rhinosinusitis", 
  "chronic rhinosinusitis with nasal polyps",
  "chronic thromboembolic pulmonary hypertension", 
  "ciliopathy",
  "cinca syndrome",
  "circadian rhythm sleep disorder, jet lag type", 
  "cirrhosis of liver",
  "citrullinemia",
  "classic familial adenomatous polyposis", 
  "classical hodgkin lymphoma",
  "clear cell adenocarcinoma",
  "clear cell meningioma", 
  "clear cell renal carcinoma",
  "clear cell renal cell carcinoma", 
  "clear cell sarcoma",
  "clear cell sarcoma of kidney",
  "clear cell sarcoma of the kidney", 
  "cll",
  "cml",
  "cocaine abuse",
  "cocaine dependence",
  "cocaine intoxication", 
  "cockayne syndrome",
  "coffin-lowry syndrome",
  "colitis",
  "colitis (disease)", 
  "colon adenocarcinoma",
  "colon adenoma",
  "colon cancer",
  "colon carcinoma", 
  "colon neoplasm",
  "colon sessile serrated adenoma/polyp",
  "colonic neoplasm", 
  "colonic tubular adenoma",
  "colorectal adenocarcinoma",
  "colorectal adenoma", 
  "colorectal cancer",
  "colorectal carcinoma",
  "colorectal neoplasm", 
  "comedo",
  "common variable immunodeficiency",
  "common wart", 
  "complete androgen insensitivity syndrome",
  "complete hydatidiform mole", 
  "compression fracture",
  "condyloma",
  "congenital adrenal hyperplasia", 
  "congenital dyserythropoietic anemia",
  "congenital heart disease", 
  "congenital mesoblastic nephroma",
  "congenital myotonic dystrophy", 
  "congenital zika syndrome",
  "connective tissue disease",
  "constipation", 
  "copd",
  "corneal dystrophy",
  "cornelia de lange syndrome",
  "coronary artery calcification", 
  "coronary artery disease",
  "coronary heart disease",
  "coronary thrombosis", 
  "corticobasal degeneration",
  "cough variant asthma",
  "craniopharyngioma", 
  "craniosynostosis",
  "creutzfeldt-jakob disease",
  "crimean-congo hemorrhagic fever", 
  "critical limb ischemia",
  "crohn disease",
  "crohn's disease", 
  "cryoglobulinemia",
  "cryptococcosis",
  "cryptogenic cirrhosis", 
  "cryptorchidism",
  "cryptorchidism (disease)",
  "cryptosporidiosis", 
  "cteph",
  "cushing's disease",
  "cutaneous leishmaniasis",
  "cutaneous melanoma (disease)", 
  "cutaneous neuroendocrine carcinoma",
  "cutaneous t-cell lymphoma", 
  "cva",
  "cystadenocarcinoma",
  "cystic fibrosis",
  "cystic kidney disease", 
  "cystinosis",
  "cystitis glandularis",
  "cytomegalovirus infection", 
  "dedifferentiated liposarcoma",
  "delayed graft function",
  "demented", 
  "dementia pugilistica",
  "dementia with lewy bodies",
  "dengue", 
  "dengue disease",
  "dengue fever",
  "dengue hemorrhagic fever", 
  "depression",
  "depressive disorder",
  "dermatitis",
  "dermatofibrosarcoma", 
  "dermatofibrosarcoma protuberans",
  "dermatomyositis",
  "desmoid tumor", 
  "desmoplastic small round cell tumor",
  "diabetes",
  "diabetes mellitus", 
  "diabetes mellitus (disease)",
  "diabetes mellitus, noninsulin-dependent", 
  "diabetic",
  "diabetic foot infection",
  "diabetic nephropathy", 
  "diabetic peripheral neuropathy",
  "diamond-blackfan anemia", 
  "diarrhea",
  "diarrheal disease",
  "dic",
  "diffuse astrocytoma", 
  "diffuse cutaneous leishmaniasis",
  "diffuse intrinsic pontine glioma", 
  "diffuse large b-cell lymphoma",
  "diffuse large b-cell lymphomas", 
  "diffuse scleroderma",
  "diffuse systemic sclerosis",
  "digestive system carcinoma", 
  "dilated cardiomyopathy",
  "dili",
  "disseminated peritoneal leiomyomatosis", 
  "diverticular disease",
  "diverticulitis",
  "down syndrome",
  "dress syndrome", 
  "drug hypersensitivity syndrome",
  "drug-induced liver injury", 
  "dubowitz syndrome",
  "duchenne muscular dystrophy",
  "ductal breast carcinoma in situ", 
  "ductal carcinoma in situ",
  "dysbiosis",
  "dyskeratosis congenita", 
  "dystonia",
  "dystrophia myotonica",
  "ebola hemorrhagic fever", 
  "ebv infection",
  "ectodermal dysplasia syndrome",
  "ectrodactyly", 
  "eczema",
  "ehlers-danlos syndrome",
  "embryonal carcinoma",
  "embryonal neoplasm", 
  "embryonal rhabdomyosarcoma",
  "embryonal rhabdomyosarcoma (disease)", 
  "emphysema",
  "enchondroma",
  "endocervical adenocarcinoma",
  "endocervical carcinoma", 
  "endometrial adenocarcinoma",
  "endometrial cancer",
  "endometrial carcinoma", 
  "endometrial carcinoma (disease)",
  "endometrial stromal nodule", 
  "endometrial stromal sarcoma",
  "endometrioid adenocarcinoma", 
  "endometrioma",
  "endometriosis",
  "endometriosis (disease)",
  "endometrium adenocarcinoma", 
  "endometrium neoplasm",
  "endothelial corneal dystrophy",
  "enterovirus infection", 
  "enthesitis-related juvenile idiopathic arthritis",
  "eosinophilia", 
  "eosinophilic asthma",
  "eosinophilic bronchitis",
  "eosinophilic esophagitis", 
  "eosinophilic granulomatosis with polyangiitis",
  "ependymoblastoma", 
  "ependymoma",
  "epidermoid carcinoma",
  "epidermolysis bullosa", 
  "epilepsy",
  "epilepsy, familial adult myoclonic, 2",
  "epileptic encephalopathy", 
  "episodic kinesigenic dyskinesia 1",
  "epithelial skin neoplasm", 
  "epithelioid leiomyosarcoma",
  "epithelioid mesothelioma",
  "epithelioid sarcoma", 
  "epstein-barr virus infection",
  "epstein-barr virus-positive diffuse large b-cell lymphoma of the elderly", 
  "erdheim-chester disease",
  "erythroleukemia",
  "esophageal adenocarcinoma", 
  "esophageal atresia/tracheoesophageal fistula",
  "esophageal cancer", 
  "esophageal carcinoma",
  "esophageal neoplasm",
  "esophageal squamous cell carcinoma", 
  "esophagitis",
  "esophagitis (disease)",
  "essential thrombocythemia", 
  "essential tremor",
  "estrogen-receptor negative breast cancer", 
  "estrogen-receptor positive breast cancer",
  "ewing sarcoma", 
  "ewing sarcoma/peripheral primitive neuroectodermal tumor",
  "ewing's sarcoma", 
  "extranodal nasal nk/t cell lymphoma",
  "extranodal nk/t-cell lymphoma", 
  "extraskeletal osteosarcoma",
  "facioscapulohumeral muscular dystrophy", 
  "facioscapulohumeral muscular dystrophy 1",
  "facioscapulohumeral muscular dystrophy 2", 
  "familial adenomatous polyposis",
  "familial cerebral cavernous malformation", 
  "familial dilated cardiomyopathy",
  "familial dysautonomia",
  "familial hemophagocytic lymphohistiocytosis", 
  "familial hemophagocytic lymphohistiocytosis 5",
  "familial hyperaldosteronism type ii", 
  "familial hypercholesterolemia",
  "fanconi anemia",
  "fatty liver disease", 
  "fetal growth restriction",
  "fibrocystic breast disease",
  "fibrodysplasia ossificans progressiva", 
  "fibroids",
  "fibrolamellar hepatocellular carcinoma",
  "fibroma", 
  "fibromatosis",
  "fibromyalgia",
  "fibromyalgia syndrome",
  "fibrosarcoma", 
  "fibrous histiocytoma",
  "flavivirus infection",
  "flu",
  "focal cortical dysplasia", 
  "focal segmental glomerulosclerosis",
  "follicular lymphoma", 
  "follicular thyroid adenoma",
  "food allergy",
  "fragile x syndrome", 
  "friedreich ataxia",
  "friedreich's ataxia",
  "frontal fibrosing alopecia", 
  "frontotemporal dementia",
  "frontotemporal dementia with motor neuron disease", 
  "fuchs' endothelial dystrophy",
  "fungal infectious disease", 
  "gallbladder cancer",
  "gallbladder carcinoma",
  "gallbladder neoplasm", 
  "gallbladder tumor",
  "gallstones",
  "gastric adenocarcinoma", 
  "gastric cancer",
  "gastric carcinoma",
  "gastric neoplasm",
  "gastritis", 
  "gastritis (disease)",
  "gastroenteropancreatic neuroendocrine neoplasm", 
  "gastroesophageal reflux disease",
  "gastrointestinal carcinoma", 
  "gastrointestinal stromal tumor",
  "gastroparesis",
  "gastroparesis (disease)", 
  "generalized pustular psoriasis",
  "gerd",
  "germ cell tumor", 
  "germinoma",
  "germinoma (disease)",
  "gestational diabetes",
  "gi hemorrhage", 
  "giardiasis",
  "glandular cystitis",
  "glioblastoma",
  "glioblastoma (disease)", 
  "glioblastoma multiforme",
  "glioma",
  "glioneuronal tumor",
  "gliosarcoma", 
  "glomerulosclerosis",
  "glomus tumor",
  "glycogen storage disease i", 
  "glycogen storage disease ii",
  "goiter",
  "graft versus host disease", 
  "granulosa cell tumor",
  "graves' ophthalmopathy",
  "guillain-barre syndrome", 
  "gvhd",
  "hailey-hailey disease",
  "head and neck cancer",
  "head and neck carcinoma", 
  "head and neck squamous cell carcinoma",
  "hearing loss",
  "hearing loss disorder", 
  "heart disease",
  "heart failure",
  "hemangioma",
  "hemangiopericytoma", 
  "hematologic disease",
  "hematoma",
  "hematopoietic and lymphoid system neoplasm", 
  "hemorrhage",
  "henoch-schoenlein purpura",
  "henoch-schonlein purpura nephritis", 
  "hepatic cancer",
  "hepatic failure",
  "hepatitis",
  "hepatitis a", 
  "hepatitis b",
  "hepatitis c",
  "hepatitis d",
  "hepatitis e",
  "hepatoblastoma", 
  "hepatocellular adenoma",
  "hepatocellular carcinoma",
  "hepatoma", 
  "hepatosplenic t-cell lymphoma",
  "her2 positive breast carcinoma", 
  "hereditary hemochromatosis",
  "hereditary leiomyomatosis and renal cell cancer", 
  "hereditary nonpolyposis colon cancer",
  "hereditary sensory and autonomic neuropathy type 1", 
  "hereditary sensory neuropathy",
  "hereditary spastic paraplegia 3a", 
  "heritable pulmonary arterial hypertension",
  "hermansky-pudlak syndrome", 
  "hern",
  "herpes simplex",
  "herpes simplex encephalitis",
  "herpes simplex infectious disease", 
  "herpes simplex type i",
  "hidradenitis suppurativa",
  "hippocampal sclerosis", 
  "histiocytoma",
  "histiocytosis",
  "hiv infection",
  "hiv infectious disease", 
  "hiv positive",
  "hiv-1 infection",
  "hives",
  "hodgkin's lymphoma", 
  "hodgkins lymphoma",
  "human african trypanosomiasis",
  "human granulocytic ehrlichiosis", 
  "human t-lymphotropic virus 1 infectious disease",
  "humoral rejection", 
  "huntington disease",
  "huntington's disease",
  "hydatidiform mole", 
  "hydrops fetalis (disease)",
  "hyper igd syndrome",
  "hyper-ige recurrent infection syndrome 1", 
  "hyper-ige syndrome",
  "hypereosinophilia",
  "hyperimmunoglobulinemia d with periodic fever", 
  "hyperkeratosis",
  "hyperlactatemia",
  "hypernephroma",
  "hyperplastic polyposis syndrome", 
  "hypersensitivity",
  "hypertension",
  "hypertensive",
  "hypertensive heart disease", 
  "hypertrichosis",
  "hypertrophic cardiomyopathy",
  "hypogammaglobulinemia", 
  "hypopharyngeal cancer",
  "hypopharynx squamous cell carcinoma", 
  "hypophosphatasia",
  "hypopigmentation-punctate palmoplantar keratoderma syndrome", 
  "hypoplastic left heart syndrome",
  "hypothyroidism",
  "hypotonia", 
  "hypoxic",
  "ibd",
  "ichthyosis",
  "ichthyosis vulgaris",
  "iddm", 
  "iddm 1",
  "idiopathic inflammatory myopathy",
  "idiopathic interstitial pneumonia", 
  "idiopathic intracranial hypertension",
  "idiopathic membranous glomerulonephritis", 
  "idiopathic pulmonary fibrosis",
  "iga glomerulonephritis",
  "igan1", 
  "immunodeficiency-centromeric instability-facial anomalies syndrome", 
  "inclusion body myositis",
  "infarction",
  "infectious diarrhea", 
  "infertility",
  "infertility disorder",
  "inflammatory arthritis", 
  "inflammatory bowel disease",
  "inflammatory breast carcinoma", 
  "influenza",
  "insulin resistance",
  "insulinoma",
  "intellectual disability", 
  "interstitial cystitis",
  "interstitial nephritis",
  "interstitial pneumonia", 
  "intestinal atresia",
  "intestinal cancer",
  "intestinal metaplasia", 
  "intestinal obstruction",
  "intestinal perforation",
  "intestinal volvulus", 
  "intimal sarcoma",
  "intracerebral hemorrhage",
  "intracranial aneurysm", 
  "intracranial hemorrhage",
  "intraductal papillary mucinous neoplasm", 
  "intraepidermal carcinoma",
  "intraepithelial neoplasia",
  "intrahepatic cholangiocarcinoma", 
  "invasive bladder cancer",
  "invasive breast carcinoma",
  "invasive ductal breast cancer", 
  "invasive ductal breast carcinoma",
  "invasive lobular breast carcinoma", 
  "irritable bowel syndrome",
  "ischemic cardiomyopathy",
  "ischemic stroke", 
  "isolated ectopia lentis",
  "isolated polycystic liver disease", 
  "japanese encephalitis",
  "juvenile arthritis",
  "juvenile dermatomyositis", 
  "juvenile idiopathic arthritis",
  "juvenile myoclonic epilepsy", 
  "juvenile nasopharyngeal angiofibroma (disease)",
  "juvenile xanthogranuloma", 
  "kallmann syndrome",
  "kaposi's sarcoma",
  "kennedy disease",
  "keratitis", 
  "keratoacanthoma",
  "keratoconus",
  "keratopathy",
  "kidney angiomyolipoma", 
  "kidney cancer",
  "kidney neoplasm",
  "kidney tumor",
  "kindler syndrome", 
  "klinefelter syndrome",
  "klinefelter's syndrome",
  "krukenberg carcinoma", 
  "krukenberg tumor",
  "langerhans cell histiocytosis",
  "large cell carcinoma", 
  "large cell lung cancer",
  "large-cell immunoblastic lymphoma", 
  "laryngeal cancer",
  "laryngeal carcinoma",
  "laryngeal squamous cell carcinoma", 
  "latent tuberculosis",
  "left ventricular hypertrophy",
  "left ventricular noncompaction", 
  "legionnaires' disease",
  "leiomyoblastoma",
  "leiomyoma",
  "leiomyosarcoma", 
  "leishmaniasis",
  "leishmaniasis, diffuse cutaneous",
  "leprosy", 
  "leukemia",
  "leukemia (disease)",
  "leukoplakia",
  "lewy body dementia", 
  "li-fraumeni syndrome",
  "lichen planus, oral",
  "limited systemic sclerosis", 
  "lip and oral cavity carcinoma",
  "lipoblastoma",
  "liposarcoma", 
  "lissencephaly",
  "lissencephaly (disease)",
  "listeria infection", 
  "listeria monocytogenes infection",
  "liver cancer",
  "liver carcinoma", 
  "liver cirrhosis",
  "liver disease",
  "liver failure",
  "liver hemangioma", 
  "liver metastases",
  "liver neoplasm",
  "liver neuroendocrine carcinoma", 
  "liver tumor",
  "liver tumour",
  "lobular breast carcinoma in situ", 
  "locally advanced breast cancer",
  "loeys-dietz syndrome",
  "long qt syndrome", 
  "low grade fibromyxoid sarcoma",
  "low grade glioma",
  "luminal b breast carcinoma", 
  "lung adenocarcinoma",
  "lung adenocarcinoma in situ",
  "lung cancer", 
  "lung carcinoma",
  "lung giant cell carcinoma",
  "lung mass",
  "lung nodule", 
  "lung sarcomatoid carcinoma",
  "lupus erythematosus",
  "lupus nephritis", 
  "lyme disease",
  "lymph node neoplasm",
  "lymphangiectasia",
  "lymphangiectasis", 
  "lymphangioleiomyomatosis",
  "lymphangioma",
  "lymphatic filariasis", 
  "lymphedema",
  "lymphoblastic leukemia",
  "lymphoblastic lymphoma", 
  "lymphocytic colitis",
  "lymphoid leukemia (disease)",
  "lymphoid neoplasm", 
  "lymphoma",
  "lymphoproliferative disorder",
  "lymphoproliferative syndrome", 
  "lynch syndrome",
  "lynch syndrome 1",
  "lytic metastatic bone lesion", 
  "macroglobulinemia",
  "macrophage activation syndrome",
  "macular degeneration", 
  "maculopathy",
  "major depression",
  "major depressive disorder", 
  "malaria",
  "malignant biphasic mesothelioma",
  "malignant epithelioid mesothelioma", 
  "malignant glioma",
  "malignant melanoma",
  "malignant mesenchymoma", 
  "malignant pancreatic neoplasm",
  "malignant peripheral nerve sheath tumor", 
  "malignant peripheral nerve sheath tumour",
  "malignant pleural mesothelioma", 
  "malignant testicular germ cell tumor",
  "mammary gland tumor", 
  "mammoplasty",
  "mantle cell lymphoma",
  "marfan syndrome",
  "marginal zone lymphoma", 
  "mast cell leukemia",
  "mastocytosis",
  "mature t-cell and nk-cell non-hodgkin lymphoma", 
  "mature teratoma",
  "maxillary sinus neoplasm",
  "mds",
  "measles", 
  "mediastinal mass",
  "medullary breast carcinoma",
  "medullary thyroid cancer", 
  "medullary thyroid gland carcinoma",
  "medulloblastoma",
  "melanocytic nevus", 
  "melanoma",
  "melanoma (disease)",
  "melanoma skin",
  "melanotic neuroectodermal tumor", 
  "melas syndrome",
  "membranous nephropathy",
  "meningeal tuberculosis", 
  "meningioma",
  "meningitis",
  "meningitis (disease)",
  "meningococcal infection", 
  "menopausal",
  "merkel cell carcinoma",
  "merrf syndrome",
  "mers", 
  "mesenchymal cell neoplasm",
  "mesial temporal lobe epilepsy with hippocampal sclerosis", 
  "mesothelioma",
  "metabolic syndrome",
  "metaplastic breast carcinoma", 
  "metastatic breast cancer",
  "metastatic carcinoma",
  "metastatic colorectal cancer", 
  "metastatic gastric cancer",
  "metastatic melanoma",
  "metastatic neoplasm", 
  "metastatic prostate carcinoma",
  "metastatic renal cell carcinoma", 
  "metastatic squamous cell carcinoma",
  "methotrexate-associated lymphoproliferation", 
  "microcephaly",
  "microcephaly (disease)",
  "microinvasive gastric cancer", 
  "mitchell-riley syndrome",
  "mitochondrial disease",
  "mitochondrial encephalomyopathy", 
  "mitochondrial myopathy",
  "mixed connective tissue disease", 
  "mixed germ cell tumor",
  "mixed neoplasm",
  "monoclonal gammopathy", 
  "monocytic leukemia",
  "monosomy",
  "monosomy 21",
  "monosomy 22", 
  "monosomy x",
  "motor neuron disease",
  "mucinous adenocarcinoma", 
  "mucinous cystadenocarcinoma",
  "mucinous ovarian cancer",
  "mucinous tubular and spindle renal cell carcinoma", 
  "mucocutaneous lymph node syndrome",
  "mucopolysaccharidosis type 1", 
  "mucosal leishmaniasis",
  "mucosal melanoma",
  "multiple myeloma", 
  "multiple myeloma progression",
  "multiple sclerosis",
  "multiple system atrophy", 
  "mumps",
  "mumps infectious disease",
  "muscular dystrophy",
  "myasthenia gravis", 
  "mycobacterial infection",
  "mycosis fungoides",
  "mycosis fungoides/sezary syndrome", 
  "myeloblastic leukemia",
  "myelocytic leukemia",
  "myelodysplastic syndrome", 
  "myelodysplastic syndrome with excess blasts",
  "myelodysplastic syndrome with excess blasts-1", 
  "myelodysplastic syndrome with excess blasts-2",
  "myelodysplastic syndromes", 
  "myelodysplastic/myeloproliferative neoplasm",
  "myelofibrosis", 
  "myeloid leukemia",
  "myeloid neoplasm",
  "myeloma",
  "myeloproliferative neoplasm", 
  "myocardial infarction",
  "myocarditis",
  "myoclonic epilepsy", 
  "myoepithelial tumor",
  "myofibromatosis",
  "myopathy",
  "myositis", 
  "myotonic dystrophy",
  "myotonic dystrophy type 1",
  "myxofibrosarcoma", 
  "myxoid leiomyosarcoma",
  "myxoid liposarcoma",
  "myxosarcoma", 
  "nakajo-nishimura syndrome",
  "narcolepsy",
  "nasal cavity carcinoma", 
  "nasal cavity polyp",
  "nasal polyp",
  "nasopharyngeal angiofibroma", 
  "nasopharyngeal carcinoma",
  "nasopharyngitis",
  "natural killer-cell leukemia", 
  "neck mass",
  "necrotizing enterocolitis",
  "neoplasm",
  "neoplasm of esophagus", 
  "neoplasm with perivascular epithelioid cell differentiation", 
  "nephritis",
  "nephropathy",
  "nephrotic syndrome",
  "neurilemmoma", 
  "neuroblastoma",
  "neurocytoma",
  "neurodevelopmental disorder", 
  "neuroendocrine carcinoma",
  "neuroendocrine neoplasm",
  "neuroendocrine tumor", 
  "neuroepithelioma",
  "neurofibroma",
  "neurofibromatosis",
  "neuronal ceroid lipofuscinosis 3", 
  "nevus",
  "niddm",
  "nk-cell leukemia",
  "nodular basal cell carcinoma", 
  "nodular goiter (disease)",
  "nomid",
  "non-alcoholic fatty liver", 
  "non-alcoholic fatty liver disease",
  "non-alcoholic steatohepatitis", 
  "non-functioning pituitary adenoma",
  "non-hodgkin lymphoma", 
  "non-hodgkin's lymphoma",
  "non-ischemic cardiomyopathy",
  "non-proliferative retinopathy", 
  "non-small cell lung cancer",
  "non-small cell lung carcinoma (disease)", 
  "non-specific interstitial pneumonia",
  "non-syndromic pontocerebellar hypoplasia", 
  "non-syndromic x-linked intellectual disability",
  "nonpapillary renal cell carcinoma", 
  "norrie disease",
  "null syndrome",
  "nut midline carcinoma",
  "obesity", 
  "obesity disorder",
  "obsessive-compulsive disorder",
  "obstructive sleep apnea syndrome", 
  "ocular melanoma",
  "oligoastrocytoma",
  "oligodendroglioma",
  "open-angle glaucoma", 
  "oral cavity carcinoma",
  "oral cavity squamous cell carcinoma", 
  "oral lichen planus",
  "oral mucosa leukoplakia",
  "oral submucous fibrosis", 
  "orf",
  "oropharyngeal cancer",
  "osteoarthritis",
  "osteoarthritis, knee", 
  "osteoblastoma (disease)",
  "osteomyelitis",
  "osteomyelitis (disease)", 
  "osteonecrosis",
  "osteoporosis",
  "osteosarcoma",
  "otofaciocervical syndrome 1", 
  "ovarian adenocarcinoma",
  "ovarian cancer",
  "ovarian carcinoma", 
  "ovarian clear cell cancer",
  "ovarian clear cell carcinoma", 
  "ovarian clear cell tumor",
  "ovarian cyst",
  "ovarian cyst (disease)", 
  "ovarian endometrioid adenocarcinoma",
  "ovarian germ cell tumor", 
  "ovarian neoplasm",
  "ovarian serous adenocarcinoma",
  "ovarian serous cystadenocarcinoma", 
  "ovarian small cell carcinoma",
  "overgrowth syndrome",
  "paget disease", 
  "pancreas cancer",
  "pancreatic adenocarcinoma",
  "pancreatic adenosquamous carcinoma", 
  "pancreatic cancer",
  "pancreatic carcinoma",
  "pancreatic ductal adenocarcinoma", 
  "pancreatic insulinoma",
  "pancreatic intraductal papillary-mucinous neoplasm", 
  "pancreatic neuroendocrine tumor",
  "papillary adenocarcinoma", 
  "papillary carcinoma",
  "papillary serous cystadenocarcinoma", 
  "papillary thyroid cancer",
  "papilloma",
  "paraganglioma",
  "paragangliomas 4", 
  "parathyroid adenoma",
  "parathyroid gland adenoma",
  "parathyroid tumor", 
  "parkinson disease",
  "parkinson's disease",
  "paroxysmal atrial fibrillation", 
  "paroxysmal nocturnal hemoglobinuria",
  "partial deletion of the long arm of chromosome 7", 
  "partial duplication of the long arm of chromosome 15",
  "pediatric meningioma", 
  "pediatric osteosarcoma",
  "pelvic mass",
  "pelvic organ prolapse, susceptibility to", 
  "pemphigus",
  "pemphigus foliaceus",
  "pemphigus vulgaris",
  "penile cancer", 
  "pericardial effusion",
  "periodontitis",
  "peripartum cardiomyopathy", 
  "peripheral nervous system neoplasm",
  "peripheral primitive neuroectodermal tumor", 
  "peripheral t-cell lymphoma, not otherwise specified",
  "peritoneal neoplasm", 
  "perlman syndrome",
  "pertussis",
  "peters anomaly",
  "phaeochromocytoma", 
  "pharyngeal cancer",
  "pharyngeal squamous cell carcinoma",
  "pharynx cancer", 
  "pharynx neoplasm",
  "pheochromocytoma",
  "phlebothrombosis",
  "phosphaturic mesenchymal tumor", 
  "piebaldism",
  "pigmented villonodular synovitis",
  "pilocytic astrocytoma", 
  "pituitary adenoma",
  "pituitary gland adenoma",
  "plasma cell leukemia", 
  "plasma cell myeloma",
  "plasma cell neoplasms",
  "plasmablastic lymphoma", 
  "plasmacytoma",
  "plasmodium falciparum malaria",
  "plasmodium vivax malaria", 
  "platelet membrane fluidity",
  "pleomorphic adenoma",
  "pleomorphic carcinoma", 
  "pleomorphic rhabdomyosarcoma",
  "pleural mesothelioma",
  "pleural tuberculosis", 
  "pleuropulmonary blastoma",
  "plexiform neurofibroma",
  "plexiform neurofibroma (disease)", 
  "pneumococcal infection",
  "pneumonia",
  "poems syndrome",
  "poikiloderma", 
  "polio",
  "poliomyelitis",
  "polycystic ovary",
  "polycystic ovary syndrome", 
  "polymyositis",
  "polyposis",
  "polysubstance abuse",
  "poorly differentiated thyroid carcinoma", 
  "poorly differentiated thyroid gland carcinoma",
  "post-transplant lymphoproliferative disease", 
  "post-traumatic stress disorder",
  "posterior polymorphous corneal dystrophy", 
  "pouchitis",
  "prader-willi syndrome",
  "pre-eclampsia",
  "precursor b-cell acute lymphoblastic leukemia", 
  "preeclampsia",
  "premature aging",
  "premenstrual dysphoric disorder", 
  "primary aldosteronism",
  "primary antiphospholipid syndrome", 
  "primary biliary cholangitis",
  "primary biliary cholangitis 1", 
  "primary central nervous system lymphoma",
  "primary cutaneous anaplastic large cell lymphoma", 
  "primary cutaneous diffuse large b-cell lymphoma, leg type", 
  "primary cutaneous follicle center lymphoma",
  "primary cutaneous t-cell non-hodgkin lymphoma", 
  "primary effusion lymphoma",
  "primary hyperparathyroidism",
  "primary hyperparathyroidism (disease)", 
  "primary mediastinal large b-cell lymphoma",
  "primary membranoproliferative glomerulonephritis", 
  "primary myelofibrosis",
  "primary peritoneal carcinoma (disease)", 
  "primary pulmonary hypertension",
  "primary sclerosing cholangitis", 
  "primitive neuroectodermal tumor",
  "pro-lymphocytic leukemia", 
  "progeria",
  "progressive familial intrahepatic cholestasis", 
  "progressive familial intrahepatic cholestasis type 2",
  "progressive multifocal leukoencephalopathy", 
  "progressive supranuclear palsy",
  "prolactin-producing pituitary gland adenoma", 
  "prolactinoma",
  "proliferative diabetic retinopathy",
  "proliferative vitreoretinopathy", 
  "prolymphocytic leukemia",
  "prostate adenocarcinoma",
  "prostate cancer", 
  "prostate carcinoma",
  "prostate intraepithelial neoplasia",
  "prostate neoplasm", 
  "prostate squamous cell carcinoma",
  "prostatic carcinoma",
  "proximal spinal muscular atrophy", 
  "pseudotumor cerebri",
  "psoriasis",
  "psoriasis vulgaris",
  "psoriatic arthritis", 
  "psoriatic plaque",
  "psychosis",
  "psychotic disorder",
  "pterygium", 
  "pulmonary arterial hypertension",
  "pulmonary aspergillosis", 
  "pulmonary blastoma",
  "pulmonary fibrosis",
  "pulmonary hypertension", 
  "pulmonary sarcoidosis",
  "pulmonary tuberculosis",
  "pustular psoriasis", 
  "q fever",
  "raeb",
  "raynaud's phenomenon",
  "recessive dystrophic epidermolysis bullosa", 
  "rectal adenocarcinoma",
  "rectal cancer",
  "rectal neoplasm", 
  "recurrent pregnancy loss",
  "relapsing multiple sclerosis",
  "relapsing-remitting multiple sclerosis", 
  "renal cancer",
  "renal carcinoma",
  "renal cell adenocarcinoma", 
  "renal cell carcinoma",
  "renal clear cell carcinoma",
  "renal disease", 
  "renal medullary carcinoma",
  "respiratory failure",
  "restrictive cardiomyopathy", 
  "reticulum cell sarcoma",
  "retina neoplasm",
  "retinal degeneration", 
  "retinitis pigmentosa",
  "retinoblastoma",
  "retroperitoneal mass", 
  "rett syndrome",
  "rhabdoid tumor",
  "rhabdoid tumor of the kidney", 
  "rhabdomyoma",
  "rhabdomyosarcoma",
  "rhabdomyosarcoma (disease)", 
  "rhabdosarcoma",
  "rheumatoid arthritis",
  "rheumatologic disorder", 
  "rhinitis",
  "rhinovirus infection",
  "rift valley fever",
  "right ventricular failure", 
  "salivary gland adenoid cystic carcinoma",
  "salmonella",
  "salmonellosis", 
  "sarcoidosis",
  "sarcoma",
  "sarcomatoid carcinoma",
  "sarcomatoid mesothelioma", 
  "sarcomatoid renal cell carcinoma",
  "sarcopenia",
  "schistosoma haematobium infection", 
  "schizophrenia",
  "schizophrenia (disease)",
  "schwannoma",
  "scleroderma", 
  "sclerosing cholangitis",
  "sclerosing cholangitis (disease)", 
  "scoliosis",
  "seasonal allergic rhinitis",
  "seckel syndrome", 
  "secondary infection",
  "secondary progressive multiple sclerosis", 
  "semantic dementia",
  "seminoma",
  "sepsis",
  "septic shock",
  "serous adenocarcinoma", 
  "serous cystadenocarcinoma",
  "sertoli cell-only syndrome",
  "severe pre-eclampsia", 
  "sex cord-stromal tumor",
  "sezary syndrome",
  "sezary's disease", 
  "short qt",
  "short qt syndrome",
  "sickle cell anemia",
  "sickle cell disease", 
  "signet ring cell carcinoma",
  "silver-russell syndrome",
  "simpson-golabi-behmel syndrome", 
  "sirs",
  "sjia",
  "sjogren syndrome",
  "sjogren's syndrome",
  "skin basal cell carcinoma", 
  "skin cancer",
  "skin infiltrative basal cell carcinoma",
  "skin lesion", 
  "skin squamous cell carcinoma",
  "skin tumor",
  "sle",
  "sle flare", 
  "sleep apnea",
  "sleep apnea syndrome",
  "small cell carcinoma", 
  "small cell lung cancer",
  "small cell lung carcinoma",
  "small cell sarcoma", 
  "small intestinal perforation",
  "small intestine carcinoma", 
  "small intestine neuroendocrine tumor, well differentiated, low or intermediate grade", 
  "smarca4-deficient sarcoma of thorax",
  "soft tissue neoplasm", 
  "soft tissue sarcoma",
  "solid tumor",
  "solitary fibrous tumor", 
  "somatostatinoma",
  "spermatogenic failure, y-linked, 1",
  "spherocytic anemia", 
  "spinal muscular atrophy",
  "spindle cell sarcoma",
  "spinocerebellar ataxia", 
  "spinocerebellar ataxia type 1",
  "spinocerebellar ataxia type 10", 
  "spinocerebellar ataxia type 2",
  "spitz nevus",
  "spitzoid melanoma", 
  "splenic lymphoma",
  "split hand-foot malformation 1",
  "spondyloarthropathy", 
  "sporadic amyotrophic lateral sclerosis",
  "squamous cell breast carcinoma", 
  "squamous cell carcinoma",
  "squamous cell carcinoma of the cervix", 
  "squamous cell lung carcinoma",
  "st-elevation myocardial infarction", 
  "stable angina pectoris",
  "steatohepatitis",
  "stemi",
  "stenosis", 
  "stomach cancer",
  "stroke",
  "subarachnoid hemorrhage",
  "subarachnoid hemorrhage (disease)", 
  "subependymal giant cell astrocytoma",
  "sudden sensorineural hearing loss", 
  "suicide",
  "susac syndrome",
  "swine influenza",
  "synovial sarcoma", 
  "synovial sarcoma (disease)",
  "synucleinopathy",
  "systemic lupus erythematosus", 
  "systemic lupus erythematosus (disease)",
  "systemic sclerosis", 
  "systemic-onset juvenile idiopathic arthritis",
  "t-cell acute lymphoblastic leukemia", 
  "t-cell childhood acute lymphocytic leukemia",
  "t-cell large granular lymphocyte leukemia", 
  "t-cell large granular lymphocytic leukemia",
  "t-cell leukemia", 
  "t-cell lymphoma",
  "t-cell non-hodgkin lymphoma",
  "t-cell prolymphocytic leukemia", 
  "tb meningitis",
  "temporal lobe epilepsy",
  "teratocarcinoma", 
  "teratoma",
  "testicular cancer",
  "testicular embryonal carcinoma", 
  "testicular germ cell tumor",
  "testicular non-seminomatous germ cell tumor", 
  "tetanus",
  "tetralogy of fallot",
  "thalassemia",
  "thrombocytopenia", 
  "thymic carcinoma",
  "thymoma",
  "thymoma (disease)",
  "thymus cancer", 
  "thyroid adenoma",
  "thyroid cancer",
  "thyroid carcinoma",
  "thyroid gland carcinoma", 
  "thyroid gland follicular carcinoma",
  "thyroid gland papillary carcinoma", 
  "thyroid gland undifferentiated (anaplastic) carcinoma",
  "tia", 
  "tics",
  "tongue squamous cell carcinoma",
  "tonsillitis",
  "toxoplasma gondii infection", 
  "trachoma",
  "transitional cell carcinoma",
  "treacher-collins syndrome", 
  "trichiasis",
  "trichilemmal cyst",
  "triple negative breast cancer", 
  "triple-negative breast carcinoma",
  "trisomy 11",
  "trisomy 12", 
  "trisomy 13",
  "trisomy 14",
  "trisomy 15",
  "trisomy 16",
  "trisomy 17", 
  "trisomy 18",
  "trisomy 21",
  "trisomy 22",
  "trisomy 8",
  "trisomy 9", 
  "tuberculosis",
  "tuberculous meningitis",
  "tuberous sclerosis", 
  "tuberous sclerosis complex",
  "tubular adenocarcinoma",
  "tumor liver", 
  "tumor of salivary gland",
  "tumor of uterus",
  "turner syndrome", 
  "type 1 diabetes mellitus",
  "type 1 interferonopathy",
  "type 2 diabetes mellitus", 
  "type i diabetes mellitus",
  "type ii diabetes mellitus",
  "type iv hypersensitivity disease", 
  "ulcerative colitis",
  "ulcerative colitis (disease)",
  "undifferentiated (embryonal) sarcoma", 
  "undifferentiated sarcoma",
  "unipolar depression",
  "univentricular heart", 
  "unstable angina",
  "urinary bladder cancer",
  "urinary bladder carcinoma", 
  "urinary bladder neoplasm",
  "urinary bladder small cell neuroendocrine carcinoma", 
  "urothelial carcinoma",
  "urticaria (disease)",
  "uterine carcinoma", 
  "uterine corpus leiomyoma",
  "uterine leiomyoma",
  "uterine leiomyosarcoma", 
  "uterine myomatosis",
  "uveal melanoma",
  "varicella",
  "varicella zoster", 
  "varicose disease",
  "vascular disease",
  "venezuelan equine encephalitis virus infection", 
  "vesicular stomatitis",
  "vesiculitis",
  "villonodular synovitis", 
  "visceral leishmaniasis",
  "vitiligo",
  "vivax malaria",
  "volvulus", 
  "waldenstrom macroglobulinemia",
  "walker-warburg syndrome",
  "warts", 
  "wegener's granulomatosis",
  "well-differentiated liposarcoma", 
  "werdnig-hoffmann disease",
  "west nile fever",
  "wheeze",
  "williams syndrome", 
  "wilms tumor",
  "wilson disease",
  "wiskott-aldrich syndrome", 
  "x-linked dystonia-parkinsonism",
  "x-linked hyper-igm syndrome", 
  "x-linked reticulate pigmentary disorder",
  "xanthogranuloma", 
  "xeroderma",
  "xeroderma pigmentosum",
  "xeroderma pigmentosum group a", 
  "xeroderma pigmentosum group b",
  "xeroderma pigmentosum group c", 
  "xeroderma pigmentosum group d",
  "yersinia pseudotuberculosis infectious disease", 
  "zika virus infection",
  "zika virus infectious disease")