tissue.annotations <- c(
    "blood",
    "breast",
    "lung",
    "brain",
    "peripheral blood",
    "liver", 
    "prostate gland",
    "umbilical cord blood",
    "colon",
    "embryo", 
    "thyroid gland",
    "amygdala",
    "bone marrow",
    "kidney",
    "skin", 
    "adipose tissue",
    "skin epidermis",
    "heart",
    "muscle",
    "muscle organ", 
    "endoderm",
    "pancreas",
    "retina",
    "semen",
    "umbilical vein", 
    "intestine",
    "mesoderm",
    "respiratory tube",
    "forebrain",
    "placenta", 
    "esophagus",
    "blood plasma",
    "coronary artery",
    "mammary gland", 
    "skeletal muscle organ",
    "central nervous system",
    "lymph node", 
    "pronephros",
    "stomach",
    "bladder",
    "bladder organ",
    "cerebral cortex", 
    "cornea",
    "mucosa",
    "ovary",
    "testis",
    "tonsil",
    "vertebral bone 2", 
    "gall bladder",
    "head",
    "prefrontal cortex",
    "spinal cord",
    "subcutaneous adipose tissue", 
    "urine",
    "heart left ventricle",
    "leg",
    "pituitary stalk",
    "prepuce", 
    "temporal lobe",
    "amniotic fluid",
    "chorionic villus",
    "choroid", 
    "dental pulp",
    "hypophysis",
    "jejunum",
    "neocortex",
    "pituitary gland", 
    "trachea",
    "ascites",
    "ascitic fluid",
    "bone",
    "bone tissue", 
    # "glomerular basement membrane",
    "islet of langerhans",
    "pancreatic islet", 
    "prepuce of penis",
    "smooth muscle tissue",
    "umbilical cord", 
    "adrenal gland",
    "amnion",
    "cerebrospinal fluid",
    "cortex of kidney", 
    "definitive endoderm",
    "dorsal striatum",
    "ectoderm",
    "epididymis", 
    "hindbrain",
    "left ventricle",
    "lens",
    "lens of camera-type eye", 
    "midbrain",
    "neck",
    "parathyroid gland",
    "renal cortex",
    "scalp", 
    "serum",
    "spleen",
    "thymus",
    "tongue",
    "vertebral bone 1",
    "arm", 
    "central sulcus of insula",
    "germinal center",
    # "insular cortex", 
    "liver bud",
    "oviduct",
    # "thalamic eminence",
    "abdomen",
    "aorta", 
    "blood serum",
    "bone fossa",
    "brown adipose tissue",
    "caudate nucleus", 
    "caudate putamen",
    "decidua",
    "diencephalon",
    "germ",
    "gut", 
    "ileum",
    "left colon",
    "lymph",
    "milk",
    "myotube",
    "pelvis", 
    "putamen",
    "renal pelvis",
    "right colon",
    "sclerite",
    "supraspinal nucleus", 
    "telencephalon",
    "uterine cervix",
    "uterine endometrium",
    "vastus lateralis", 
    "yolk sac",
    "abomasum",
    "archicortex",
    "barrett's esophagus", 
    "caput epididymis",
    # "communicating vessel palatocerebral artery", 
    "cyst",
    "endometrium",
    "eye",
    "fallopian tube",
    "frontal lobe", 
    "gastrocnemius",
    "heart right ventricle",
    "hippocampus",
    "lateral lumbar region of abdomen", 
    "ligament",
    "limb",
    "lower digestive tract",
    "lumbar spinal cord", 
    "mediastinum",
    # "parieto-occipital sulcus",
    "pileus",
    "posterior cranial fossa", 
    "posterior longitudinal ligament",
    "posterior subcentral sulcus", 
    "pterygium",
    "pulmonary artery",
    "right ventricle",
    "small intestine", 
    "superior frontal gyrus",
    "trunk",
    "urinary bladder",
    "amiculum of inferior olive", 
    "anterior cingulate cortex",
    "anterior hypothalamic region", 
    "basal ganglion",
    "biceps brachii",
    "biliary tree",
    "blood clot", 
    "bodily fluid",
    "bronchus",
    "buccal mucosa",
    "calcaneal tendon", 
    "cartilage",
    "cartilage tissue",
    "cerebellar cortex",
    "cerebellum", 
    "cervical cavity",
    "chorion",
    "choroid plexus",
    "clavicle bone", 
    "colorectum",
    "colostrum",
    "craniocervical region",
    "cutaneous appendage", 
    "dentate gyrus",
    "dentate gyrus of hippocampal formation",
    "diaphragm", 
    "duodenum",
    "embryoid body",
    "endoderm of foregut",
    "epidermis", 
    "fat pad",
    "fetus",
    "foregut",
    "forelimb",
    "frontal pole",
    "ganglion", 
    "ganglionic eminence",
    "gingiva",
    "gonad",
    "gonadal ridge",
    "hepatic portal vein", 
    "hindgut",
    "hypopharynx",
    "knee",
    "large intestine",
    "larynx", 
    "late embryo",
    "liver parenchyma",
    "medial ganglionic eminence", 
    "medulla oblongata",
    "mesenchyme",
    "middle frontal gyrus",
    "milk fat", 
    "morula",
    "mouth",
    "mouth floor",
    "multicellular organism",
    "muscle tissue", 
    "myometrium",
    "nasopharynx",
    "nephron",
    "nervous system cell part layer", 
    "nose",
    "occipital lobe",
    "oropharynx",
    "pancreatic epithelial bud", 
    "parietal lobe",
    "parotid gland",
    "pectoral muscle",
    "peripheral region of retina", 
    "pleura",
    "pons",
    "posterior communicating artery",
    "quadriceps", 
    "quadriceps femoris",
    "rectum",
    "rectus femoris",
    "renal medulla", 
    "renal proximal tubule",
    "reproductive system",
    "right atrium", 
    "somite",
    "sputum",
    "stroma",
    "subventricular zone",
    "superficial temporal artery", 
    "tendon",
    "thigh",
    "thorax",
    "tibialis anterior",
    "trigeminal ganglion", 
    "umbilical artery",
    "uterus",
    "vagina",
    "vein",
    "vermiform appendix", 
    "white adipose tissue",
    "abdominal adipose tissue",
    "abdominal wall", 
    "adult brain",
    "alimentary part of gastrointestinal system", 
    "anal region",
    "anatomical projection",
    "anatomical wall",
    "anterior cingulate gyrus", 
    "anterior cruciate ligament of knee joint",
    "anterior nuclear group", 
    "aorta thoracica",
    "articular cartilage",
    "articular cartilage of joint", 
    "ascending colon",
    "axillary lymph node",
    "axon tract",
    "basement membrane", 
    "body of pancreas",
    "body wall",
    "buttock",
    "caecum",
    "cardiogenic splanchnic mesoderm", 
    "carotid artery",
    "carotid artery segment",
    "caudal intralaminar nuclear group", 
    "cecum",
    "central part of mediodorsal nucleus of the thalamus", 
    "cerebellar plate",
    "chest",
    "chest wall",
    "cilium",
    "colon ascendens", 
    "colon sigmoideum",
    "colon transversum",
    "common carotid artery plus branches", 
    "cortical plate",
    "cranium",
    "deltoid",
    "dorsal thoracic segment of trunk", 
    "dorsolateral prefrontal cortex",
    "duct",
    "egg chamber",
    "egg yolk", 
    "forearm",
    "forelimb stylopod",
    "forelimb zeugopod",
    "frontal cortex", 
    "gastrocnemius medialis",
    "gastroesophageal sphincter",
    "gastrointestinal tract", 
    "habenular commissure",
    "hard palate",
    "hepatobiliary system", 
    "hindlimb",
    "hindlimb stylopod",
    "inner cell mass",
    "inner medulla of kidney", 
    "jaw",
    "jaw skeleton",
    "joint",
    "keratinocyte differentiation", 
    "lateral line primordium",
    "limb muscle",
    "lower back",
    "lower leg skin", 
    "mammary fat pad",
    "marginal zone of embryo",
    "marginal zone of spleen", 
    "medial forebrain bundle",
    "mesenchyme of umbilical cord",
    "mesendoderm", 
    "metanephric cap",
    "metanephron",
    "metanephros",
    "mucosa of rectum", 
    "muscle belly",
    "muscle cell",
    "muscle fibre",
    "nasal cavity", 
    "nasal polyp",
    "neuroepithelium",
    "omental fat pad",
    "outer medulla of kidney", 
    "ovarian cyst",
    "ovarian follicle",
    "palate",
    "pancreatic duct", 
    "paraxial mesoderm",
    "pectoral complex",
    "pelvic complex",
    "pericardium", 
    "pleural effusion",
    "posterior cingulate gyrus",
    "posterior mesenteric artery", 
    "presomitic mesoderm",
    "presumptive gut",
    "primary visual cortex", 
    "primitive endoderm",
    "proximal tubule",
    "psoas",
    "psoas muscle", 
    "reticuloendothelial system",
    "retromolar triangle",
    "right atrium auricular region", 
    "right cardiac atrium",
    "right lobe of liver",
    "saliva-secreting gland", 
    "salivary gland",
    "secretion",
    # "semicircular canal",
    "seminal plasma", 
    "sex-specific anatomical structure",
    "shoulder joint",
    "sigmoid colon", 
    "skeletal muscle tissue",
    "skin of thorax",
    "skull",
    "soleus", 
    "soleus muscle",
    "striate cortex",
    "subscapularis muscle",
    "substantia nigra", 
    "substantia nigra pars compacta",
    "substantia propria of cornea", 
    "supramarginal gyrus",
    "suprapubic skin",
    "synovia",
    "synovial fluid", 
    "tegmentum",
    "temporal cortex",
    "thoracic aorta",
    "tooth crown", 
    "transverse colon",
    "uncinate process of ethmoid",
    "upper lobe of left lung", 
    "vasculature",
    "ventral tegmental area",
    "yolk",
    "bone marrow biopsy", 
    "cervical biopsy",
    "colonic biopsy",
    "craniotomy",
    "diaphragm", 
    "effusion",
    "endoscopic biopsy",
    "liver biopsy",
    "muscle biopsy", 
    "rectal biopsy",
    "synovial biopsy")